### ISSUE TITLE
Privileged mode

### ISSUE THREAD

**Issue by bodleytunes** [srl-labs/containerlab#1012]
Hi,

Just a quick question, not sure if I'm missing something but I generated some vmx's with vrnetlab and they run fine using docker run manually using the --privileged flag but fail without it (some qemu connect error).
It seems when I deploy with containerlab they fail, and show unhealthy.
I was wondering if Containerlab deploys them with privileged by default?

If so then I can start troubleshooting elsewhere to see why its failing but at the moment I'm just curious to see if its trying to run them without privileged mode enabled.

Thanks!
Jon.

**Comment by bodleytunes** [comment]
![image](https://user-images.githubusercontent.com/619239/188206442-3da2e405-8dd9-4f3f-ad81-462e89e81280.png)

**Comment by bodleytunes** [comment]
sorry showing healthy now! I think I had not given it enough time?

**Comment by hellt** [comment]
Hi @bodleytunes 
Yes, by default privileged flag is set to true. You can monitor the boot process of a vmx with 'docker logs -f <container>'
