### ISSUE TITLE
IRC channel on Libera

### ISSUE THREAD

**Issue by netstx** [srl-labs/containerlab#1024]
Howdy all,

I've registered #containerlab on Libera IRC network - wondering if the project maintainers would like to make it an "official" channel for the project as another means of communicating? Libera provides an IRC community platform for free and open-source software and peer directed projects ([libera.chat](https://libera.chat/)).

Thanks!
Rafael

**Comment by hellt** [comment]
Hi @netstx ! 
I'm good with more chat platforms. Is there anything specific that will make IRC people find the channel easier? I'm not an IRC person myself, so wondering if a channel name and server address is enough for people to find out that channel?

**Comment by netstx** [comment]
Hi @hellt - awesome! Simply mentioning "#containerlab on Libera IRC network" or something of the sorts would suffice to spread the word. Libera has a registration process to make a channel official for the project: [https://libera.chat/chanreg/#how-to-register-as-a-project](https://libera.chat/chanreg/#how-to-register-as-a-project) - if you have time, I can ping their staff and eventually you or Karim would have to send them an e-mail, if you don't mind.
