### ISSUE TITLE
DependencyManager enhancement

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#1027]
DependencyManager was introduced with PR #976 and supported the creation of nodes with static IP addresses prior to containers with dynamic addresses.
#1013 extends the dependency creation capabilities to the implicit definition based on shared network namespaces (https://containerlab.dev/manual/nodes/#container-mode). Where the root container of a namespace needs to be started before the dependent cotnainer can be started.
#1022 Even if not related to the DependencyManager, because it simply relies on information from the Runtime (Docker, Podman, etc.) implements the dependency on external containers.
#1026 Again built upon the DependencyManager allows for explicit dependency definition via the "waitFor" stanza in the node or kind config.

All these mechanisms trigger after the simple start of the container. At least for the explicit dependency definition additional triggers might be usefull.

- PostDeploy (maybe + delay)
  PostDeploy is the phase where config is applied to the devices. They might also need some additional time to commit and "converge", hence the option for an additional delay seems to make sense.
- HealthCheck -> OK
  So when the runtimes Healthcheck turns green.

Please leave a comment with additions to these use-cases.

**Comment by hellt** [comment]
Hi @steiler 
thanks for this awesome work on the dependency manager! All three PRs have been merged 🍻

**Comment by steiler** [comment]
This was meant to be a follow up enhancement @hellt.
Now that the basics are merger I wanted, as outlined on top even allow for the wait-for stuff to define which phase to wait for.
like when Healtcheck is ok or when the config phase of clab is over instead of just the deploy phase.
So im my view this should not be closed?!

**Comment by hellt** [comment]
ah, alright.
I got a wrong conclusion

**Comment by steiler** [comment]
Well tried to implement this, but realized that there is a clear seperation between the _create_ and _configure_ phase for all containers at once. So only creating a container after another container is configured causes a deadlock.
All nodes need to make it through the create phase before configure phase starts.
I have anyways commited my actual work in progress state (https://github.com/steiler/containerlab/tree/waitforPhases) for possible later review. It covers the dependency manager pieces, runtime integration and so on. Now we would need to change deploy.go and see how to overcome the problem of the overall clear seperation of phases.
Anyways, for now I'm leaving it to it.
