### ISSUE TITLE
make SR OS to accept startup-config in partial form

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1033]
SR OS nodes must be able to accept startup config both in full form and in partial, CLI-blob-like format.
The full form is a hardcopy of a config file which is used by the node to boot from. We store this file at tftp location from which SR OS boots.

The partial config is provided in the MD-CLI format and must conform to the following structure:

1. entering into the configuration mode
2. commands to execute
3. commit command

SR OS vrnetlab code needs to be adjusted to make an analysis if the provided file contains the full config blob, or a partial command. The way to do this is under investigation.
If the full config is detected to be provided, the current startup config implementation is enforced.

If the partial config is detected, we should send the commands after the node boots, similar to how startup config is provided for XR, VMX, etc.

**Comment by steiler** [comment]
Can you provide samples of both formats, such that the format absolutely clear.

**Comment by hellt** [comment]
@steiler since I believe it is tricky to automatically detect if a config provided for SR OS is a full config or a partial one, I think it is safe to require a user to indicate that in the file itself.

A proposal is to look for the first line of the config file, and if it matches `## CONTAINERLAB PARTIAL CONFIG ##` string (case insensitive, trimmed of spaces) then this config is a partial config and is NOT a startup config.

For a partial config I propose that the rest of the file is taken as in input to the scrapli script (in python for vrnetlab-based devices) that will send the commands over to the node.

Vrnetlab code should be common to the vrnetlab (not part of SR OS lib)
