### ISSUE TITLE
Generalize checkIfSignatures to all kinds

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1060]
https://github.com/srl-labs/containerlab/blob/1ef7460784a0ee4d5358221bac9c7563da704215/clab/config.go#L681

SRL nodes aren't the only ones with specific naming requirements, vrnetlab based nodes like sros need to use 'eth[x]'

The correct interface naming pattern should be part of the kind/type definition, and (if set) should be checked generically for all node kinds

Note: was discussed in the past (https://github.com/srl-labs/containerlab/issues/377) but only partially implemented. Some users had issues with using invalid interface names, which silently breaks their topology

**Comment by steiler** [comment]
Moved to #1129 now

**Comment by hellt** [comment]
the ground work is done in #1129 
we have to add a regexp for vr-based nodes and then we can close this one
