### ISSUE TITLE
build image from Dockerfile, not pulling from registry

### ISSUE THREAD

**Issue by mdraevich** [srl-labs/containerlab#1085]
Hi there! 
Thank you guys for a great tool for testing purposes.

My question is gonna be about building images. As far as you know docker-compose includes [feature](https://docs.docker.com/compose/compose-file/build/#build-definition) that allows you to create image from Dockerfile, not only pulling a ready-to-use image from registry.

Right now I'm playing with containerlab and wondering is such feature presented within it? I can't find any reference to it...

Have a nice day,
Matthew

**Comment by hellt** [comment]
Hi @mdraevich,
the only dockerfile we expose in our repo is this one https://github.com/srl-labs/containerlab/blob/main/goreleaser.dockerfile

It is used in our build pipeline to build and upload the image to the registry. As you can see, it uses an `apk` package that is built by goreleaser.
If you need to build a binary and create an image yourself, then you will have to create your own dockerfile with build steps. That should be pretty straightforward I think.

**Comment by mdraevich** [comment]
> Hi @mdraevich, the only dockerfile we expose in our repo is this one https://github.com/srl-labs/containerlab/blob/main/goreleaser.dockerfile
> 
> It is used in our build pipeline to build and upload the image to the registry. As you can see, it uses an `apk` package that is built by goreleaser. If you need to build a binary and create an image yourself, then you will have to create your own dockerfile with build steps. That should be pretty straightforward I think.

Dear @hellt 
Sorry, I believe I messed up you with my question. Let me clarify a bit. 

I'm talking about building images for nodes in `topology.yml`. As far as I see topology nodes can use already built images only. 
As an example, `docker-compose` file allows you to create images from Dockerfile right inside `docker-compose.yml` file.

Example of how it may look:
```
topology:
  nodes:
    ready-to-use-image:
      kind: linux
      image: python:3.8
      

    use-dockerfile-to-build-new-image:
      kind: linux
      build:
        context: inside-folder/
        dockerfile: node.Dockerfile
```

Build definition may be implemented according to [docker-compose](https://docs.docker.com/compose/compose-file/build/#build-definition).

Hope it's clear right now,
Matthew

**Comment by hellt** [comment]
ah, I see
yes, this is not supported in containerlab
