### ISSUE TITLE
Add `clab pull` command

### ISSUE THREAD

**Issue by bortok** [srl-labs/containerlab#1091]
Since clab has to be run as a root/sudo, it causes issues when pulling images from private repositories – a user might have a working authentication setup, but it is being ignored when running via sudo. A solution could be similar to `docker-compose pull` command, which pulls the images listed in `compose.yml`, and if a current user is a member of `docker` group, that works w/o sudo by using current user's authentication to the private repo.

**Comment by hellt** [comment]
Hi @bortok 
I believe our current implementation should handle that already. We are pulling the auth data from the docker configuration file (that is user specific) https://github.com/srl-labs/containerlab/blob/d3f6780c521bc3f3186c57fde4990b73d1e4dcf8/runtime/docker/auth.go#L44.

Maybe when you use `sudo clab` you forget to add `sudo -E clab` to preserve original user's home dir?

**Comment by hellt** [comment]
feel free to reopen if the solution in my prev comment doesn't help

**Comment by bortok** [comment]
just ran into another example when `clab pull` would be useful – to force refresh the `latest` images
