### ISSUE TITLE
CoreOS install script not working

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#1114]
Trying to install containerlab via the script at `https://get.containerlab.dev` fails with the following error on CoreOS:

```
[root@localhost core]# bash -c "$(curl -sL https://get.containerlab.dev)"
Downloading https://github.com/srl-labs/containerlab/releases/download/v0.33.0/containerlab_0.33.0_linux_amd64.rpm
Preparing to install containerlab 0.33.0 from package
error: can't create transaction lock on /usr/share/rpm/.rpm.lock (Read-only file system)
Failed to install containerlab
        For support, go to https://github.com/srl-labs/containerlab/issues
```
It seems like on CoreOS it should be installed via `rpm-ostree install <CLAB.RPM>`

**Comment by hellt** [comment]
can you check if coreos reveals itself in `cat /etc/os-release` file or in `uname -a`

**Comment by steiler** [comment]
```
[core@localhost ~]$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="37.20221106.3.0 (CoreOS)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora CoreOS 37.20221106.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='37.20221106.3.0'
[core@localhost ~]$ uname -a
Linux localhost.localdomain 6.0.7-301.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 4 18:35:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

so I guess we should check if version contains `CoreOS`
and make that an additional branch here: https://github.com/srl-labs/containerlab/blob/main/get.sh#L209

**Comment by hellt** [comment]
@steiler I think we should introduce another function `setPkgInstaller()` that will set a variables `$PKG_INSTALLER` to one of the

* `dpkg -i` - for deb packages
* `rpm -U` - for rpm packages
* `rpm-ostree -U` - for rpm packages where `/etc/os-release` contains CoreOS in the version string

and then here https://github.com/srl-labs/containerlab/blob/82337e36b168ffcdb9863ddb74e39759e99c27ce/get.sh#L207-L211 we just call `sudo $PKG_INSTALLER $TMP_FILE`

**Comment by steiler** [comment]
It would be `rpm-ostree install` I assume, but I'm not familiar enought with CoreOS.

**Comment by hellt** [comment]
yes, I dont have it installed either, so someone with coreos installed should be able to vet this
but `rpm-ostree install` can be the one that is needed, the only tricky part there is that it needs to support upgrading (that is what `-U` flag does on centos)

**Comment by steiler** [comment]
Have a VM running ... just the install would not work... let me figure that stuff out

**Comment by steiler** [comment]
This does the magic:
`rpm-ostree install --idempotent --uninstall=containerlab <RPMFile/RPMURL>`

**Comment by hellt** [comment]
added in #1115
