### ISSUE TITLE
unable to make project.

### ISSUE THREAD

**Issue by jkary** [srl-labs/containerlab#1159]
Hi Dodin!

Thank you for all your hard work on containerlab!

I'm working on debugging an issue and when I run make I'm getting an unauthorized response for "https://ghcr.io/v2/hellt/godot/manifests/1.4.11".  

Can you help?
Jason

**Comment by hellt** [comment]
Hi @jkary 
Should be fixed now. Please try again

**Comment by hellt** [comment]
To build a project though you can use 'make build'. godot is used for formatting the code, not necessary for build stage

**Comment by jkary** [comment]
Thank you sir!
