### ISSUE TITLE
Containerisation of vSRX

### ISSUE THREAD

**Issue by jk2lx** [srl-labs/containerlab#1178]
While cSRX is supported by containerlab, it would be helpful if vSRX is supported as well since there is a large feature gap between the two products and vSRX is more suitable to simulate a physical SRX:
https://apps.juniper.net/feature-explorer/compare-multiple.html?pkey=20600616%7CvSRX%7CNA%7C%7C21900003%7CcSRX%7CNA&platforms=vSRX%7CNA%7C%7CcSRX%7CNA

**Comment by hellt** [comment]
Hi @jk2lx 
would you mind testing boxen that claims support for vsrx?
https://github.com/carlmontanari/boxen/

**Comment by mtucker502** [comment]
Seems there is a pull request for this in main vrnet:
https://github.com/vrnetlab/vrnetlab/pull/140

**Comment by hellt** [comment]
@mtucker502 yep, if someone ports this to [hellt/vrnetlab](https://github.com/hellt/vrnetlab/) I will review and merge

**Comment by hellt** [comment]
This is now done in #1352 and https://github.com/hellt/vrnetlab/pull/112
