### ISSUE TITLE
Allow to specify a path for artifacts

### ISSUE THREAD

**Issue by jk2lx** [srl-labs/containerlab#1179]
By default containerlab stores the artifacts in the current directory.
This results in artifacts being stored in random places depending on the directory the user was at.
If an artifact path could be specified in the topology file, the artifacts would always be stored in a predictable path.

**Comment by hellt** [comment]
I think we can start with having an environment variable, without touching the clab yml structure.

**Comment by hellt** [comment]
Delivered in #1248
will be part of the next release
