### ISSUE TITLE
`inspect --all` doesn't list ignite (or non-default) runtime containers

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1202]
as discovered in #1171

**Comment by networkop** [comment]
I suppose you need something like `clab.WithAllRuntimes()` where you build and initialise as many runtimes as you can (assuming some of them will fail the `Init()` call)

**Comment by steiler** [comment]
it would not be too bad keeping an index to keep track of which topologies and thereby which containers where deployed also using which runtimes. We could store this in a common folder, like /usr/local/containerlab/<idx_file>.
This would also help figuring out relastions from containers that do not have our custom containerlab labels (e.g. kind).

**Comment by hellt** [comment]
ignite is not in the scope right now, closing until there is more interest
