### ISSUE TITLE
Interface naming verification breaks cEOS lab

### ISSUE THREAD

**Issue by ankudinov** [srl-labs/containerlab#1203]
Looks like since clab 0.35.0 there is some interface naming verification in place.
The following configuration is not working any more:

```yaml
  links:
  - endpoints: ["spine1:et1_1", "leaf1:et2_1"]
```

The following error is produced:
> Error: arista cEOS node "spine1" has an interface named "et1_1" which doesn't match the required pattern. Interfaces should be named as ethX or etX, where X is >1

Same configuration works well with 0.34.0 and supposed to produce interface names like `Ethernet1/1`, etc. without using user defined interface mapping.
It's basically a very convenient undocumented shortcut, that is not possible in clab 0.35.0.
Is there a way to disable this check already? If not, can it be changed to something more flexible?

**Comment by steiler** [comment]
Hi @ankudinov,
we have already noticed an issue with the regex and it seems like @hellt has already released v0.35.1 https://github.com/srl-labs/containerlab/releases/tag/v0.35.1  so give that one a try.

**Comment by ankudinov** [comment]
Yes. 15 min ago. =) Just tested. 0.35.1 fixed it.
Leaving this open if anybody wants to mention the underscore trick in cEOS section. Otherwise close.

**Comment by hellt** [comment]
Ah, I see you added clarifications in #1204
