### ISSUE TITLE
Introduce `image-pull-policy` for node specification

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1221]
Introduce per-node property (with kind and defaults levels) that drives the image-pull-policy behavior

**Comment by steiler** [comment]
today we are looking up the image locally and if it exists we use it. If not we pull it.
What behaviour are you after? preventing pulling or forcing the pulling? Or do we need both?

**Comment by hellt** [comment]
@steiler current behavior stays (equals to IfNotPresent), we have to add Always and Never

https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
