### ISSUE TITLE
Allow web URLs for files consistently

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1331]
Containerlab has a bunch of places where external files are referenced. In some cases (like startup-config) this can be a URL, but in other cases (like srl-agents) this can only be local files

It would be helpful if any external files referenced could be located anywhere, either on the web or on the local file system. Specifically in case of agent YAML files, this would allow the user to reference a centrally maintained/updated file for an agent, as opposed to having to create a local copy (which becomes stale)

**Comment by steiler** [comment]
For the agent config, would we need to force a specific file ending?
we have functionality that extracts the filename from the last url part and the content-disposition header.
However if this agent-config would maybe come from a pastebin, ther will very likely be no or no proper file ending.
we could enforce so.
opinions @hellt, @jbemmel ?

**Comment by jbemmel** [comment]
The agent config is (should be) YAML, so if the URL does not end with ".yml" we could add that

**Comment by hellt** [comment]
done in #1336
