### ISSUE TITLE
Consider forking weaveworks/ignite

### ISSUE THREAD

**Issue by gaby** [srl-labs/containerlab#1351]
Containerlab is the biggest project using `weaveworks/ignite` right now. The project seems to have been abandoned since weaveworks is now focused on `gitops`. It may be worth for containerlab to fork and at least update deps for ignite.

Rel https://github.com/weaveworks/ignite/issues/971

**Comment by hellt** [comment]
Hi @gaby 
We are using the fork done by @networkop. Looks like for now it does all that is needed.

**Comment by gaby** [comment]
@hellt Your go.mod still points to weaveworks though:

https://github.com/srl-labs/containerlab/blob/main/go.mod#L39

**Comment by hellt** [comment]
@gaby https://github.com/srl-labs/containerlab/blob/8c9b54fccf407d5903d235ef48c863563736867c/go.mod#L295

**Comment by gaby** [comment]
> @gaby
> 
> https://github.com/srl-labs/containerlab/blob/8c9b54fccf407d5903d235ef48c863563736867c/go.mod#L295

😁 Didn't see that. Seems like even that one still has the CNI issue. Ignite was never updated to cni v1.0.0 while containerlab does use it. Not sure if that's an issue 🤔

Just wanted to make sure that containerlab was aware of ignite being abandoned.

**Comment by hellt** [comment]
We are not using it much to be honest. Only cumulus nodes leverage ignite, and a few corner cases for Linux containers. 

We wont maintain it either, all the hope is with @networkop :)

**Comment by networkop** [comment]
Yep, feel free to tag me in any ignite-related issues. I'll try to keep it alive for as long as it makes sense.
