### ISSUE TITLE
Implement a check for `ip_tables` and `ip6_tables` kernel module

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1360]
VM-based nodes require iptables module to be loaded to perform datapath stitching.
Newer OSes betray iptables and not have it loaded by default.

We have to start checking if iptables module is loaded and if not emit a warning in logs

**Comment by steiler** [comment]
So what do you think should be preconditions to do the check?
Shall this be checked on every execution? Nodekind dependent or also dependent on runtime or a combination of these?

**Comment by hellt** [comment]
Checking it every time. Even when no VM-based nodes are used, we use iptables to create rules for external lab access.
So on start we should check for ip_tables ip6_tables modules and emit a WARN if they are not loaded.

**Comment by hellt** [comment]
In #1363 the auto-load of ip and ip6_tables kernel modules is implemented
