### ISSUE TITLE
Arista cEOS Management1 Interface

### ISSUE THREAD

**Issue by paullavelle** [srl-labs/containerlab#1469]
Currently, Arista cEOS nodes launched in Containerlab use Management0 as the default management interface. Although this can be overridden by creating an EosIntfMapping.json file, it is preferable for Containerlab to use Management1 as the default management interface, aligning it with vEOS and EOS running on physical switches.

**Comment by hellt** [comment]
@burnyd @sulrich does it match your view, guys?

**Comment by ankudinov** [comment]
I'd rather prefer a simple knob TBH as that can break some existing labs if the default will be simply changed.

**Comment by ankudinov** [comment]
One more concern is that if the fix will be to set a default mapping JSON, we have to make sure that "e1_1" -> "Ethernet1/1" conversion still works. As mapping JSON kills this possibility when set. And building complex topology with underscore is much easier than defining a full interface map.

**Comment by paullavelle** [comment]
Closing issue as it is possible to specify Ma1 via EosIntfMapping.json if required:

{
  "ManagementIntf": {
    "eth0": "Management1"
  },
...

**Comment by paullavelle** [comment]
Closing issue as it is possible to specify Ma1 via EosIntfMapping.json if required:

{
"ManagementIntf": {
"eth0": "Management1"
},
...
