### ISSUE TITLE
Error when running "linux" containers over Podman

### ISSUE THREAD

**Issue by q2dg** [srl-labs/containerlab#1483]
I've commented this issue in https://github.com/srl-labs/containerlab/issues/643#issuecomment-1647607722 , but I reference it here for visibility.

**Comment by hellt** [comment]
Hi
Podman is still in the experimental phase. We are not (actively) supporting it and rely on the community to steer it forward if needed.

**Comment by steiler** [comment]
@q2dg you might want to take a look at the container I assume it stopped or crashed.
Take a look at the logs of the container.

**Comment by q2dg** [comment]
Well, they are empty...I suspect because they not even get to be started. I attach a screenshot 

![Captura de pantalla de 2023-07-27 13-46-55](https://github.com/srl-labs/containerlab/assets/7274874/b2d4c446-957f-44e2-8640-fcd1dba727ad)

Thanks!!

**Comment by q2dg** [comment]
Oooh..it was that!!! The missing entrypoint!! Now it works perfectly with (root-ful) Podman!
Thanks a lot!!! (and sorry for the inconvenience!)
