### ISSUE TITLE
YAML parsing of endpoints var in topology

### ISSUE THREAD

**Issue by thinghacker** [srl-labs/containerlab#1509]
version: 0.43.0
 commit: c90be25c

I have a toplogy file that I am attempting to play with the templating concept, however I am not having getting my topology file parsed when I add vars to an endpoint - something like this (truncated topology file)
```
  links:
    - endpoints: [R1:eth1, R2:eth1]
      vars:
        port: [1/1/c1, 1/1/c1]
        clab_link_ip: 192.168.1.0/31
```

When I try to test it, I get an error

```$ sudo containerlab config -t simple.yml template --vars
Error: failed to read topology file: yaml: unmarshal errors:
  line 27: field vars not found in type struct { Type string "yaml:\"type\""; Endpoints interface {} "yaml:\"endpoints\"" }
Consult with release notes to see if any fields were changed/removed
```

I tried to do something a bit simpler but recieved a similar warning
```
  links:
    - endpoints: [R1:eth1, R2:eth1]
      mtu: 1500
```

Is there a problem with parsing things  under endpoints or am I doing something wrong?
```
$ sudo containerlab config -t simple.yml template --vars
Error: failed to read topology file: yaml: unmarshal errors:
  line 27: field mtu not found in type struct { Type string "yaml:\"type\""; Endpoints interface {} "yaml:\"endpoints\"" }
Consult with release notes to see if any fields were changed/removed
```

**Comment by steiler** [comment]
Hi, first of all thanks for reporting this issue.
Let us take a look at this. But chances are high that this is a bug. We have changed the parsing of endpoints via the last release.
You might want to try v0.42.0 to see if it shows the same error.

**Comment by thinghacker** [comment]
Thankyou for the quick response! Rolling back to 0.42.0 resolved my problem
