### ISSUE TITLE
clab supports version 1.0 of OVS bridges. Need support to up to 1.5

### ISSUE THREAD

**Issue by pdumais** [srl-labs/containerlab#1538]
it is impossible to set the OVS bridge to protocols=OpenFlow13 using ovs-vsctl before launching clab. We can set the protocol version after clab is launched. But this complicates automation scripts. It would be nice to get that fixed.

The solution is to change the parameters of the connection that the ovs library creates.
It should be as easy as doing `client := ovs.New(goOvs.Sudo(), ovs.FlowFormat("OXM-OpenFlow15"), ovs.Protocols("OpenFlow15"))` 
Then the client would support all bridge versions up to 1.5

I have not tried this yet but I'm working on something to be able to test with 1.0 and all versions to 1.5. Once I can confirm the solution works, I can submit a PR.

**Comment by hellt** [comment]
Looks like #1539 addresses just pre-condition of this feature request?

**Comment by steiler** [comment]
Feedback from @pdumais: can closed
