### ISSUE TITLE
When destroying a lab, OVS ports are not completely cleaned up

### ISSUE THREAD

**Issue by pdumais** [srl-labs/containerlab#1540]
The veth pair is deleted but the bridge still has the interface that was created with "ovs-vsctl add-port". The interface is in error state and show that no underlying device exists because the veth was deleted. It doesn't cause any issue, but it would be cleaner to remove the dnagling interface from the bridge.

I can fix it.
Can someone advise where this cleanup should be done? This would need to be done with  c.VSwitch.DeletePort.
Probably right before deleting the netlink device but we'd check if the veth is part of an ovs bridge.

**Comment by pdumais** [comment]
PR #1545

**Comment by hellt** [comment]
thanks @pdumais !
