### ISSUE TITLE
Log if a config from labdir is used

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1554]
It is often unknown to users that the presence of the config in the labdir would indicate to containerlab to use this config, instead of a default "empty" config.

We have to add an INFO log message saying that for node X the config is loaded from file Y

**Comment by steiler** [comment]
there should already be a log message.
See https://github.com/srl-labs/containerlab/blame/main/nodes/default_node.go#L236
Anyways I propose simplifying the if else. See #1560
