### ISSUE TITLE
containerlab fails when sr os node fails to boot and partial config is used

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1570]
When SR OS fails to properly load (e.g. when wrong/expired license is used) clab fails to apply the partial config:

<img width="1011" alt="image" src="https://github.com/srl-labs/containerlab/assets/5679861/713c3a36-a6ae-42ca-8344-d07ea5fcfdf6">

**Comment by steiler** [comment]
What is it we expect here?
Just failing gracefully or do you have anything else in mind?

**Comment by hellt** [comment]
Graceful exit with a log message saying that the node failed to start successfully. Check container logs

**Comment by steiler** [comment]
@hellt 
Looking at it, this seems to be the same as in #1722.
Back then the `fmt.Error` was on line 255 See version v0.44.3:
https://github.com/srl-labs/containerlab/blob/v0.44.3/nodes/vr_sros/vr-sros.go#L255C3-L255C10
With #1723 I think we can close this.

**Comment by hellt** [comment]
good catch.
I will wait for a user to confirm the fix and merge #1723 after/

**Comment by hellt** [comment]
correct, should be exactly that.
Fixed by #1723
