### ISSUE TITLE
Cisco xrd ssh error

### ISSUE THREAD

**Issue by eayetsi** [srl-labs/containerlab#1579]
I tried to do a lab of srl Linux and Cisco xrd as provided by the documentation. I am able to login the Nokia srl using ssh but with the Cisco xrd, I am not able to ssh. I get no route to host ssh error when I tried to ssh into the node. All other nodes works except the xrd. I have not change anything with the startup config shared in the lab yml file.

**Comment by hellt** [comment]
Check boot log
docker logs <container name>

**Comment by eayetsi** [comment]
below are the logs i get when i run the docker logs --details <docker name>

ctrace_enable_configuration(): inotify_init() failed. Too many open files (24)
 ctrace_enable_configuration2 failed with error 0x2
 ctrace_enable_configuration(): inotify_init() failed. Too many open files (24)
 ctrace_enable_configuration2 failed with error 0x2
 ctrace_enable_configuration(): inotify_init() failed. Too many open files (24)
 ctrace_enable_configuration2 failed with error 0x2
 ctrace_enable_configuration(): inotify_init() failed. Too many open files (24)
 ctrace_enable_configuration2 failed with error 0x2

**Comment by eayetsi** [comment]
I cannot even ping the node (172.20.20.2)

**Comment by steiler** [comment]
Try increasing /proc/sys/fs/inotify/max_user_instances

see e.g. https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total

**Comment by eayetsi** [comment]
@steiler and @hellt Thanks a lot. after increasing /proc/sys/fs/inotify/max_user_instances it is working now. I really appreciate the help.

**Comment by eayetsi** [comment]
Thanks
