### ISSUE TITLE
Unable to view graph

### ISSUE THREAD

**Issue by eayetsi** [srl-labs/containerlab#1582]
Hello All,

Anytime I use the graph function in containerlab, I get https://0.0.0.0:(port number). I have deployed the containerlab on ESXI and I access it remotely over the public internet. I don't know whether it is because I am accessing it over the internet. Any help?

**Comment by hellt** [comment]
Hi
you should be able to access it using your public IP/DNS name and the provided port. Granted you have no/allowed firewall rules.

**Comment by eayetsi** [comment]
You mean the public IP of the server or my source IP address. I have firewall policy in place on the Ubuntu. I will allow the port on the Ubuntu firewall.

**Comment by hellt** [comment]
if you VM with containerlab has public IP address, then you should be able to reach the graph UI using that public IP. Mind the firewall rules

**Comment by eayetsi** [comment]
Thanks a lot
