### ISSUE TITLE
Post "https://clab-ixiac01-ixia-c/config": dial tcp 172.20.20.2:443: connect: connection refused exit status 1

### ISSUE THREAD

**Issue by cgo-chong** [srl-labs/containerlab#1611]
Hi，I encountered a problem when learning this example 'https://containerlab.dev/lab-examples/ixiacone-srl/#__tabbed_1_2’. Could you help me? 

root@VM-0-8-ubuntu:/home/ubuntu/containerlab/lab-examples/ixiac01# clab inspect
INFO[0000] Parsing & checking topology file: ixiac01.clab.yml 
+---+---------------------+--------------+------------------------------------------------------+---------------------+---------+----------------+----------------------+
| # |        Name         | Container ID |                        Image                         |        Kind         |  State  |  IPv4 Address  |     IPv6 Address     |
+---+---------------------+--------------+------------------------------------------------------+---------------------+---------+----------------+----------------------+
| 1 | clab-ixiac01-ixia-c | b68567dee459 | ghcr.io/open-traffic-generator/ixia-c-one:0.0.1-3865 | keysight_ixia-c-one | running | 172.20.20.2/24 | 2001:172:20:20::2/64 |
| 2 | clab-ixiac01-srl    | 450aed07a2e4 | ghcr.io/nokia/srlinux                                | srl                 | running | 172.20.20.3/24 | 2001:172:20:20::3/64 |
+---+---------------------+--------------+------------------------------------------------------+---------------------+---------+----------------+----------------------+

root@VM-0-8-ubuntu:/home/ubuntu/containerlab/lab-examples/ixiac01# go run dshaw.go -dstMac="aa:c1:ab:61:8a:64"
2023/09/27 17:46:18 OTG configuration:
flows:
- duration:
    choice: fixed_packets
    fixed_packets:
      gap: 12
      packets: 10000
  metrics:
    enable: true
    loss: false
    timestamps: false
  name: p1.v4.p2
  packet:
  - choice: ethernet
    ethernet:
      dst:
        choice: value
        value: aa:c1:ab:61:8a:64
      src:
        choice: value
        value: aa:c1:ab:57:ba:2f
  - choice: ipv4
    ipv4:
      dst:
        choice: value
        value: 10.2.2.1
      src:
        choice: value
        value: 10.1.1.1
  rate:
    choice: pps
    pps: "100"
  size:
    choice: fixed
    fixed: 512
  tx_rx:
    choice: port
    port:
      rx_name: p2
      tx_name: p1
ports:
- location: eth1
  name: p1
- location: eth2
  name: p2

2023/09/27 17:46:18 Post "https://clab-ixiac01-ixia-c/config": dial tcp 172.20.20.2:443: connect: connection refused
exit status 1

**Comment by cgo-chong** [comment]
The go program is below:

`package main

import (
	"flag"
	"log"
	"time"

	"github.com/open-traffic-generator/snappi/gosnappi"
)

// hostname and interfaces of ixia-c-one node from containerlab topology
const (
	otgHost  = "https://clab-ixiac01-ixia-c:8443"
	otgPort1 = "eth1"
	otgPort2 = "eth2"
)

var (
	dstMac   = "aa:c1:ab:61:8a:64"
	srcMac   = "aa:c1:ab:57:ba:2f"
	pktCount = 10000
)

func main() {
	// replace value of dstMac with actual MAC of DUT interface connected to otgPort1
	flag.StringVar(&dstMac, "dstMac", dstMac, "Destination MAC address to be used for all packets")
	flag.Parse()

	api, config := newConfig()

	// push traffic configuration to otgHost
	res, err := api.SetConfig(config)
	checkResponse(res, err)

	// start transmitting configured flows
	ts := api.NewTransmitState().SetState(gosnappi.TransmitStateState.START)
	res, err = api.SetTransmitState(ts)
	checkResponse(res, err)

	// fetch flow metrics and wait for received frame count to be correct
	mr := api.NewMetricsRequest()
	mr.Flow()
	waitFor(
		func() bool {
			res, err := api.GetMetrics(mr)
			checkResponse(res, err)

			fm := res.FlowMetrics().Items()[0]
			return fm.Transmit() == gosnappi.FlowMetricTransmit.STOPPED && fm.FramesRx() == int64(pktCount)
		},
		20*time.Second,
	)
}

func checkResponse(res interface{}, err error) {
	if err != nil {
		log.Fatal(err)
	}
	switch v := res.(type) {
	case gosnappi.MetricsResponse:
		log.Printf("Metrics Response:\n%s\n", v)
	case gosnappi.ResponseWarning:
		for _, w := range v.Warnings() {
			log.Println("WARNING:", w)
		}
	default:
		log.Fatal("Unknown response type:", v)
	}
}

func newConfig() (gosnappi.GosnappiApi, gosnappi.Config) {
	// create a new API handle to make API calls against otgHost
	api := gosnappi.NewApi()
	api.NewHttpTransport().SetLocation(otgHost).SetVerify(false)

	// create an empty traffic configuration
	config := api.NewConfig()
	// create traffic endpoints
	p1 := config.Ports().Add().SetName("p1").SetLocation(otgPort1)
	p2 := config.Ports().Add().SetName("p2").SetLocation(otgPort2)
	// create a flow and set the endpoints
	f1 := config.Flows().Add().SetName("p1.v4.p2")
	f1.TxRx().Port().SetTxName(p1.Name()).SetRxName(p2.Name())

	// enable per flow metrics tracking
	f1.Metrics().SetEnable(true)
	// set size, count and transmit rate for all packets in the flow
	f1.Size().SetFixed(512)
	f1.Rate().SetPps(100)
	f1.Duration().FixedPackets().SetPackets(int32(pktCount))

	// configure headers for all packets in the flow
	eth := f1.Packet().Add().Ethernet()
	ip := f1.Packet().Add().Ipv4()

	eth.Src().SetValue(srcMac)
	eth.Dst().SetValue(dstMac)

	ip.Src().SetValue("10.1.1.1")
	ip.Dst().SetValue("10.2.2.1")

	log.Printf("OTG configuration:\n%s\n", config)
	return api, config
}

func waitFor(fn func() bool, timeout time.Duration) {
	start := time.Now()
	for {
		if fn() {
			return
		}
		if time.Since(start) > timeout {
			log.Fatal("Timeout occurred !")
		}

		time.Sleep(500 * time.Millisecond)
	}
}`

**Comment by hellt** [comment]
pinging @bortok

**Comment by bortok** [comment]
There a contradiction in the OTG URL `dshaw.go` is supposed to use: 
```
otgHost = "https://clab-ixiac01-ixia-c:8443/"
```
vs what is in the log: 
```
2023/09/27 17:46:18 Post "https://clab-ixiac01-ixia-c/config": dial tcp 172.20.20.2:443: connect: connection refused
```

@cgo-chong could you double check which TCP port are you using to connect to Ixia-c? 

Note, we changed the default TCP port Ixia-c is listening on from `443` to `8443` starting with version [v0.0.1-3662](https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-3662) but the older Ixia-c images would still listen on `443`. The lab example in the containerlab repo is using the old image `0.0.1-2755`.

**Comment by cgo-chong** [comment]
> There a contradiction in the OTG URL `dshaw.go` is supposed to use:
> 
> ```
> otgHost = "https://clab-ixiac01-ixia-c:8443/"
> ```
> 
> vs what is in the log:
> 
> ```
> 2023/09/27 17:46:18 Post "https://clab-ixiac01-ixia-c/config": dial tcp 172.20.20.2:443: connect: connection refused
> ```
> 
> @cgo-chong could you double check which TCP port are you using to connect to Ixia-c?
> 
> Note, we changed the default TCP port Ixia-c is listening on from `443` to `8443` starting with version [v0.0.1-3662](https://github.com/open-traffic-generator/ixia-c/releases/tag/v0.0.1-3662) but the older Ixia-c images would still listen on `443`. The lab example in the containerlab repo is using the old image `0.0.1-2755`.

Hi, I use the command in the 'clab-ixiac01-ixia-c' container and see the output below:
![image](https://github.com/srl-labs/containerlab/assets/145850775/1826f1e0-4ec7-4547-8752-8274f3dc8cc9)

**Comment by cgo-chong** [comment]
![image](https://github.com/srl-labs/containerlab/assets/145850775/8451eaa4-ae34-4f54-aa50-ea1240982b4c)
I used the command 'docker ps'，and got the picture above.

**Comment by bortok** [comment]
I see you're using ixia-c ver 3865, which runs on port 8443. Please update your go script to use such port instead of 443.

**Comment by cgo-chong** [comment]
I'm really sorry that I used to upload the wrong 'dshaw.go’ program in which I actually use 'otgHost  = "https://clab-ixiac01-ixia-c"' rather than 'otgHost  = "https://clab-ixiac01-ixia-c:8443'.

But I encountered another problem. It seems that  ‘srl.cfg’ didn't work. The ip address didn't config correctly  in the container 'clab-ixiac01-srl'. And I'm trying to solve it.


root@VM-0-8-ubuntu:/home/ubuntu/containerlab/lab-examples/ixiac01# docker exec -it clab-ixiac01-srl bash 
[root@srl /]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: dummy-mgmt0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 6a:ff:40:6d:da:d9 brd ff:ff:ff:ff:ff:ff
    inet 172.20.20.2/24 brd 172.20.20.255 scope global dummy-mgmt0
       valid_lft forever preferred_lft forever
    inet6 2001:172:20:20::2/64 scope global 
       valid_lft forever preferred_lft forever
3: gway-2801@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether f6:92:fb:59:2e:c8 brd ff:ff:ff:ff:ff:ff link-netns srbase-mgmt
    inet6 fe80::f492:fbff:fe59:2ec8/64 scope link 
       valid_lft forever preferred_lft forever
4: gway-2800@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c6:ab:7c:e3:d8:ea brd ff:ff:ff:ff:ff:ff link-netns srbase-default
    inet6 fe80::c4ab:7cff:fee3:d8ea/64 scope link 
       valid_lft forever preferred_lft forever
5: e1-1-0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether de:6b:04:84:f0:9c brd ff:ff:ff:ff:ff:ff link-netns srbase-default
    inet6 fe80::dc6b:4ff:fe84:f09c/64 scope link 
       valid_lft forever preferred_lft forever
6: e1-2-0@if5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether e6:bf:65:c0:b2:89 brd ff:ff:ff:ff:ff:ff link-netns srbase-default
8: monit_in@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9234 qdisc noqueue state UP group default qlen 1000
    link/ether d6:fd:d6:d9:24:4a brd ff:ff:ff:ff:ff:ff link-netns monit
    inet6 fe80::d4fd:d6ff:fed9:244a/64 scope link 
       valid_lft forever preferred_lft forever
9: mgmt0-0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a2:d2:59:37:f4:85 brd ff:ff:ff:ff:ff:ff link-netns srbase-mgmt
    inet6 fe80::a0d2:59ff:fe37:f485/64 scope link 
       valid_lft forever preferred_lft forever
41: mgmt0@if42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1514 qdisc noqueue state UP group default 
    link/ether 02:42:ac:14:14:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
45: e1-1@if46: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9232 qdisc noqueue state UP group default 
    link/ether 1a:c6:01:ff:00:01 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::a8c1:abff:fecd:c4ff/64 scope link 
       valid_lft forever preferred_lft forever
47: e1-2@if48: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9232 qdisc noqueue state UP group default 
    link/ether 1a:c6:01:ff:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::a8c1:abff:feda:bd0b/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by hellt** [comment]
you should create another issue with showing which config doesn't work and formatting code snippets with monospace using three backticks
