### ISSUE TITLE
Auto-provisioning of DNS servers for SR Linux

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1638]
SR Linux management is a separate network namespace which doesn't share the DNS of the root netns setup by docker.

Because of that, users who want to get internet/external access from the management (or any other) net-inst have to configure DNS manually.

We can improve this a bit by

1. figuring out which DNS servers are configured on the host
2. adding these dns entries in the SRL config template

This will remove one of the tedious workflows of adding DNS servers manually, because often you can't just add 1.1.1.1 or 8.8.4.4 and you need to use the DNS servers of the cloud environment your VM is on.

## finding DNS addresses

It all starts with DNS addresses. They can be found in `/etc/resolv.conf` for older systems and in `sudo resolvectl status <interface>` on newer distros.
We have to check both and add addresses from both if both exist.

To find which interface DNS addresses to use we should use rtnetlink and finding a route to 8.8.8.8 and the interface that is returned for this addr.

## Configuring DNS entries
<img width="404" alt="image" src="https://github.com/srl-labs/containerlab/assets/5679861/a42dfbc5-4bd4-4e82-b41c-4e5f6806a885">

**Comment by hellt** [comment]
DNS in srl should be configured via srlinux config

**Comment by hellt** [comment]
Do you mean to use this file to read which DNS servers are configured in the system to populate it in the srl config?

**Comment by steiler** [comment]
yes. We do not need to run any route lookup or anything, just take the two files, extract the ip from the `nameserver <ip>` lines and we're all good. Take a look at above PR.
