### ISSUE TITLE
Feature: Check for and download 'latest' image

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1652]
I recently had a lab fail because it contained the 'latest' image for SR Linux, and a colleague had a different version of 'latest' deployed locally

When the image name contains the 'latest' tag, Containerlab should check if the latest image is indeed available, and pull an update if not

**Comment by steiler** [comment]
Hi Jeroen,
this behaviour is in line with docker-compose. Anyways, if you always want to latest image and to perform the check you can define the image-pull-policy as documented here:
https://containerlab.dev/manual/nodes/#image-pull-policy

**Comment by hellt** [comment]
Given that we have a knob aligned with default behavior of docker/k8s we are not considering changing the default
