### ISSUE TITLE
Remote topo deploy to support pull request URLs

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1694]
URLs like https://github.com/srl-labs/srl-telemetry-lab/pull/28 would be dope to support
That way people could test PRs opened against the labs effortlessly

**Comment by steiler** [comment]
Well from here (https://github.com/srl-labs/srl-telemetry-lab/pull/28) the pullable / deployable url is just a single click away ... not sure if it is thaatttt beneficial

**Comment by hellt** [comment]
@steiler you mean by using `https://github.com/dBitech/srl-labs.srl-telemetry-lab/tree/23.7.2_and_friends` as an url?
