### ISSUE TITLE
Help with openvswitch

### ISSUE THREAD

**Issue by eayetsi** [srl-labs/containerlab#1807]
Hello All,

Please I need help in creating openvswitch for containerlab. I created one and when I reference it in the yaml topology, I get below error.
INFO[0000] Containerlab v0.49.0 started
INFO[0000] Parsing & checking topology file: ceos-test.yml
**_**Error: interface vSwitch:port1 is defined via topology but does already exist: <nil>
interface vSwitch:port2 is defined via topology but does already exist: <nil>**_**

Please any help will be much appreciated. Thanks a lot

**Comment by eayetsi** [comment]
Below is my ovs details


labserver@lab:~/clab$ sudo ovs-vsctl show
db49f99e-7da0-49fc-909b-ff6320e8d9af
    Bridge br-bridge
        Port brp1
            Interface brp1
                type: internal
        Port br-bridge
            Interface br-bridge
                type: internal
        Port brp2
            Interface brp2
                type: internal
    ovs_version: "2.17.8

**Comment by sacckth** [comment]
> Below is my ovs details
> 
> labserver@lab:~/clab$ sudo ovs-vsctl show db49f99e-7da0-49fc-909b-ff6320e8d9af Bridge br-bridge Port brp1 Interface brp1 type: internal Port br-bridge Interface br-bridge type: internal Port brp2 Interface brp2 type: internal ovs_version: "2.17.8
Can you please share you full YAML topology?

**Comment by eayetsi** [comment]
Please find below the full YAML topology as requested.

# Arista Ceos with vSwitch test

name: ceos-test
prefix: ""

topology:
  nodes:
    R1:
      kind: ceos
      image: ceos:4.30.3M
    R2:
      kind: ceos
      image: ceos:4.30.3M
    br-bridge:
      kind: ovs-bridge

  links:
    - endpoints: ["R1:eth1", "br-bridge:brp1"]
    - endpoints: ["R2:eth1", "br-bridge:brp2"]

**Comment by eayetsi** [comment]
Hello All,

I have been able to find my way out. 
Thanks a lot
