### ISSUE TITLE
srlinux 23.10 and macvlan

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1867]
macvlan interface on srl side seems to be in the down state
https://discord.com/channels/854262008589058058/854262008589058061/1204796952475344906

we need to check

**Comment by benbgg** [comment]
had partial success by making sure MTUs match (Partial - ie tcpdump shows traffic, ipv6 RA gets through, arp resolution happens, but no unicast forwarding)

**Comment by hellt** [comment]
will close this to see if it resurfaces with more recent srl versions
