### ISSUE TITLE
Cisco 8000

### ISSUE THREAD

**Issue by berkutcloud** [srl-labs/containerlab#1901]
Dear team,

we are looking to get the details how to create container image for Cisco 8000 in the same way as other containers. Sadly, this explanation doesn't really seem to be in a spirit of Open Source: https://github.com/hellt/vrnetlab/issues/169

We are happy to collaborate on creating the image, but we need to get that explained or clear marks that is is not possible to run Cisco 8000 on containerlab.

Regards,
Berkut Cloud

**Comment by hellt** [comment]
added by @mzagozen in v0.54.0 

https://containerlab.dev/manual/kinds/vr-c8000v/
