### ISSUE TITLE
MTU is printed as unicode char.

### ISSUE THREAD

**Issue by ik5pvx** [srl-labs/containerlab#1910]
Hello,

On startup, the following information is printed:

```
INFO[0000] Containerlab v0.51.3 started                 
INFO[0000] Parsing & checking topology file: confedtest.clab.yml 
INFO[0000] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU='ל' 
```
The MTU is 1500 and that character corresponds:

```
0x05DC	1500	HEBREW LETTER LAMED	
```

(https://www.ssec.wisc.edu/~tomw/java/unicode.html#x0590)

Bug is probably here:
https://github.com/srl-labs/containerlab/blob/f11d4a93b9abae2968f586ff5582bc299989e7eb/runtime/docker/docker.go#L189

%d instead of %q maybe?

Cheers

Pf

**Comment by hellt** [comment]
yeah, this was a fun issue. You're right @ik5pvx
