### ISSUE TITLE
KinD: kubeconfig is created in root user's home directory by default

### ISSUE THREAD

**Issue by YutaroHayakawa** [srl-labs/containerlab#1913]
ContainerLab enforces executing the `deploy` command with PID=0. Usually, it can be accomplished by executing the `containerlab` command with `sudo`. When the KinD is used, KinD creates a kubeconfig file to interact with the created cluster. The default path is `$HOME/.kube/config`. However, since we are creating the kind cluster in the root user context, it is created in `/root/.kube/config`. Because of this behavior, after the `containerlab deploy`, we cannot start using the k8s cluster with `kubectl` from the original user.

For example,

```
$ cat topo.yaml
name: kind01
topology:
  nodes:
    k01:
      kind: k8s-kind
    k01-control-plane:
      kind: ext-container
    server:
      kind: linux
      image: nicolaka/netshoot:latest
$ sudo containerlab -t topo.yaml deploy
...
$ kubectl cluster-info

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

The last kubectl fails because the default search path of `kubectl` is `$HOME/.kube/config` and it is not `/root/.kube/config` (when running with root user, it should succeeds).

I'd like to make the above workflow work without any extra effort (e.g., specifying KUBECONFIG env var). However, don't have any particular solution at the moment.

**Comment by hellt** [comment]
Hi
Did you try with 'sudo -E ...'?

**Comment by YutaroHayakawa** [comment]
Ah, good point. With `-E`, $HOME will be preserved, so it works well.

**Comment by hellt** [comment]
But we had a function that we use to automatically derive the homedir for other bits. So we can hopefully leverage it for kind as well, that way even if you forget to add -E flag the homedir of a sudo user will be used

**Comment by YutaroHayakawa** [comment]
Sounds cool. Thanks! Let me close this issue.
