### ISSUE TITLE
Dead links restored

### ISSUE THREAD

**Issue by blinklet** [srl-labs/containerlab#1921]
Regarding Pull Request #1909 "Fix Dead Links", which was recently merged. I wanted to let you know that I fixed the web site problem that caused you to comment out the links. If you want, you may restore them. I also set up monitoring so I will know if my web site goes down again.

**Comment by hellt** [comment]
thnx, restored in https://github.com/srl-labs/containerlab/commit/865751390b6b6bb01994058eb336c3ec3ae00404
