### ISSUE TITLE
Linux bridge does not work

### ISSUE THREAD

**Issue by akaliwod** [srl-labs/containerlab#1945]
Hey, trying to deploy basic topology with linux bridge node type. 

```
name: demo
topology:
  nodes:
    br-linux:
      kind: bridge
    n1:
      kind: linux
      image: alpine:latest
    n2:
      kind: linux
      image: alpine:latest
  links:
    - endpoints: ["br-linux:eth1", "n1:eth1"]
    - endpoints: ["br-linux:eth2", "n2:eth1"]
```

Bridge is pre-created: brctl addbr br-linux. No errors are thrown even when using -d flag. Interfaces eth1 and eth2 get created however, they are not connected to br-linux and effectively after adding IP address to linux:eth1, there is no communication via bridge

```
# brctl show br-linux
bridge name     bridge id               STP enabled     interfaces
br-linux                8000.da639d1e96f1       no
```

containerlab: 0.52.0
host: fedora 36

Thanks for advice

**Comment by hellt** [comment]
Hi, unfortunately I can't reproduce

```
❯ clab version
  ____ ___  _   _ _____  _    ___ _   _ _____ ____  _       _     
 / ___/ _ \| \ | |_   _|/ \  |_ _| \ | | ____|  _ \| | __ _| |__  
| |  | | | |  \| | | | / _ \  | ||  \| |  _| | |_) | |/ _` | '_ \ 
| |__| |_| | |\  | | |/ ___ \ | || |\  | |___|  _ <| | (_| | |_) |
 \____\___/|_| \_| |_/_/   \_\___|_| \_|_____|_| \_\_|\__,_|_.__/ 

    version: 0.52.0
```

```yaml
name: br1

topology:
  nodes:
    l1:
      kind: linux
      image: alpine:3

    br-test:
      kind: bridge

  links:
    - endpoints: ["br-test:l1eth1", "l1:eth1"]
```

```
❯ clab dep -c -t private/linux-br.clab.yml 
INFO[0000] Containerlab v0.52.0 started                 
INFO[0000] Parsing & checking topology file: linux-br.clab.yml 
INFO[0000] Removing /root/srl-labs/containerlab/clab-br1 directory... 
INFO[0000] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU=1450 
INFO[0000] Creating lab directory: /root/srl-labs/containerlab/clab-br1 
INFO[0000] Creating container: "l1"                     
INFO[0000] Created link: br-test:l1eth1 <--> l1:eth1    
INFO[0000] Adding containerlab host entries to /etc/hosts file 
INFO[0000] Adding ssh config for containerlab nodes     
+---+-------------+--------------+----------+-------+---------+----------------+----------------------+
| # |    Name     | Container ID |  Image   | Kind  |  State  |  IPv4 Address  |     IPv6 Address     |
+---+-------------+--------------+----------+-------+---------+----------------+----------------------+
| 1 | clab-br1-l1 | cc8d7f8358c1 | alpine:3 | linux | running | 172.20.20.2/24 | 2001:172:20:20::2/64 |
+---+-------------+--------------+----------+-------+---------+----------------+----------------------+
```
And the link is there
```
❯ brctl show | grep br-test
br-test         8000.72bb2dc45d9d       no              l1eth1
```

**Comment by akaliwod** [comment]
Hi, thanks for checking, could you share your working setup details? I am using VM with fedora 36 as runtime environment. I have not done any specific system configuration changes besides installing necessary packages for containerlab application. Maybe it is OS related...

**Comment by akaliwod** [comment]
I have recreated full setup on ubuntu 20.04LTS and linux bridge is correctly configured with interfaces

```
br-linux                8000.aac1ab5c308f       no              eth1
                                                        eth2
```

However, once I have configured eth1 on each apline linux, there is no communication (ping) between then via linux bridge unfortunately...

If linux containers are deployed back-to-back (i.e. without linux bridge), they are IP reachable via theirs eth1 interface.

**Comment by hellt** [comment]
you can check with tcpdump where do the packets drop in your case.
Could be iptables or other firewall's rules

**Comment by akaliwod** [comment]
it works just fine on ubuntu 20.04LTS (forgot to bring bridge interface up). on fedora 36, all interfaces are not added to linux brigde.

**Comment by hellt** [comment]
this is weird, though.
we have fedora users and they never mentioned anything like that...
But ok, if you are happy with running debian/ubuntu then you are not blocked anymore

**Comment by ChrisHills463** [comment]
I am having the same problem with Fedora 41 - 2 out of 4 clients are connected to the bridge, and even then, those two clients are not able to communicate with one another.
