### ISSUE TITLE
Update default SRL image version used in lab examples

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1987]
https://github.com/srl-labs/containerlab/blob/57dc41ae4ecf25799bae0bb8597861d61502e4b9/lab-examples/clos03/cfg-clos.clab.yml#L13

Can we switch to 24.3.1 please?

**Comment by hellt** [comment]
this is a bit challenging for this lab specifically.
The reason is we do not maintain Config Engine, hence this lab was never updated. I think I will have a thought or two about removing it...

**Comment by hellt** [comment]
removed in #2002
