### ISSUE TITLE
Rocky 9.1: Unable to load kernel module "ip_tables" automatically

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1988]
```
WARN[0036] Unable to load kernel module "ip_tables" automatically "load ip_tables failed: exec format error"
```

Manually:
```
modprobe ip_tables
```

Has no issues

**Comment by gdluca** [comment]
same for ip6_tables.

**Comment by mrmrcoleman** [comment]
I'm also seeing this: Ubuntu 24.04 (LTS) x64

`WARN[0000] Unable to load kernel module "ip6_tables" automatically "load ip6_tables failed: exec format error"`

**Comment by mrmrcoleman** [comment]
Tested the same OS version on Equinix Metal and it works fine, so this problem is limited to Digital Ocean for me

**Comment by hellt** [comment]
These warnings won't prevent you from enjoying clab.
