### ISSUE TITLE
Move exec to configure stage?

### ISSUE THREAD

**Issue by bewing** [srl-labs/containerlab#1998]
Is there a reason that running the "execs" is outside of the configure stage?

I have a lab where I need to execute `exec`s on nodes in a specific order.  I was hoping "wait-for stage configure" would allow the downstream nodes to wait for the upstream node to finish its execs, but it appears all of them enter the stage at the same time, given that execs start after marking configure done:

https://github.com/srl-labs/containerlab/blob/2328c9821b45ccfc0dbe1e5383fccb13a8b9c4c0/clab/clab.go#L627-L630

**Comment by hellt** [comment]
You can run execs on each stage

https://containerlab.dev/rn/0.52/#per-stage-exec

It is just that the default (node scoped) exec is run after the post deploy

**Comment by bewing** [comment]
Awesome!

```
stages:
  configure:
    exec:
      on-exit:
```

is the sauce I was looking for!

**Comment by steiler** [comment]
![image](https://github.com/srl-labs/containerlab/assets/1122166/fa09db0c-44b0-4790-a20f-188fd45ff4ac)   ;-)
