### ISSUE TITLE
Installation of APK on Alpine fails with error 127

### ISSUE THREAD

**Issue by andi-blafasl** [srl-labs/containerlab#2018]
I tried to install the release APK on a fresh installed Alpine container but it failed with error 127. The post install script "postinstall.sh" uses the shebang /bin/bash which is not available on Alpine images. It doesn't make much sense that the script first action is to check if /bin/bash exists. I created a [pull request](https://github.com/srl-labs/containerlab/pull/2017) to change the shebang to /bin/sh.
I tested the script on Alpine, and it worked as expected.

**Comment by hellt** [comment]
thanks @andi-blafasl 
I wonder if it makes sense to also change the script to be POSIX compatible by replacing `&>` with an explicit redirect -- https://www.shellcheck.net/wiki/SC3020

I used shellcheck.net 

<img width="1081" alt="image" src="https://github.com/srl-labs/containerlab/assets/5679861/27252d81-4eca-4746-b3db-08148d14118d">

**Comment by hellt** [comment]
had a quick minute and addit it to the PR

**Comment by andi-blafasl** [comment]
any chance to get a release with this fix?
