### ISSUE TITLE
Add an option to disable file acls (facl)

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#2027]
File ACLs sometimes give us problems when the topo is deployed on a network location (nfs).

A deployment option to not use facls is a quick workaround until/unless a proper fix is found.

see [internal discussion](https://teams.microsoft.com/l/message/19:e4b5ce27ba1e46bfa683bc679c7814fc@thread.tacv2/1713797389114?tenantId=5d471751-9675-428d-917b-70f44f9630b0&groupId=ceac81ac-cfa8-473c-99a0-1b1444b5d95d&parentMessageId=1713797389114&teamName=containerlab&channelName=General&createdTime=1713797389114).

**Comment by steiler** [comment]
deployment option or env var?
