### ISSUE TITLE
Installing on an IPv6 only host

### ISSUE THREAD

**Issue by jenslink** [srl-labs/containerlab#2030]
Just tried to install containerlab in an IPv6 only host. Which doesn't work because apt.fury.io does not have IPv6. :-( 

$ host apt.fury.io 
apt.fury.io is an alias for asymmetrical-lavender-v7hkfdon7i8y6ly9e04vlvjw.herokudns.com.
asymmetrical-lavender-v7hkfdon7i8y6ly9e04vlvjw.herokudns.com has address 54.209.91.188
asymmetrical-lavender-v7hkfdon7i8y6ly9e04vlvjw.herokudns.com has address 54.221.251.148
asymmetrical-lavender-v7hkfdon7i8y6ly9e04vlvjw.herokudns.com has address 54.204.238.15
asymmetrical-lavender-v7hkfdon7i8y6ly9e04vlvjw.herokudns.com has address 75.101.184.39

**Comment by hellt** [comment]
What was your installation option? Did you use the script or tried the installation via the package manager?

**Comment by jenslink** [comment]
Upss. Forgot that detail. Sorry. I tried the package manager.

**Comment by jenslink** [comment]
You could switch to another provider.

**Comment by jenslink** [comment]
Or we all could ask hello@gemfury.com for IPv6 support.

**Comment by hellt** [comment]
at the time we didn't have anyone providing free hosting for deb/rpm/apk pkgs for OSS projects.
if you happen to know one, do share

**Comment by jenslink** [comment]
> Or we all could ask [hello@gemfury.com](mailto:hello@gemfury.com) for IPv6 support. They are using AWS so IPv6 should be no big deal.

Got an answer: Use https://netdevops.fury.site/apt/ instead.

**Comment by hellt** [comment]
oh sweet, I reached out to packagecloud as well, so we have two options now
