### ISSUE TITLE
Environment variables in Clab topology files do not work with clab destroy command

### ISSUE THREAD

**Issue by micabrer-arista** [srl-labs/containerlab#2056]
Topology files can have environment variables stored anywhere in the file - expressed commonly as ${ENV_VAR_EXAMPLE}.

These work well when specifying them in areas like the lab name field or the version field in the "kinds:" section when deploying a containerlab.

However when using the clab destroy command with a topology file that uses environment variables, it doesn't seem like these are expanded and so the destroy fails.

For example: 

`root@containerlab:/home/micabrer/containerlab# clab destroy -d -t Templates/dual-dc.clab.yml

DEBU[0000] env runtime var value is

DEBU[0000] Running runtime.Init with params &{Timeout:2m0s GracefulShutdown:false Debug:false KeepMgmtNet:false VerifyLinkParams:<nil>} and &{Network: Bridge: IPv4Subnet: IPv4Gw: IPv4Range: IPv6Subnet: IPv6Gw: IPv6Range: MTU:0 ExternalAccess:<nil>}

DEBU[0000] Runtime: Docker

DEBU[0000] detected docker network mtu value - 1500

DEBU[0000] initialized a runtime with params &{config:{Timeout:120000000000 GracefulShutdown:false Debug:false KeepMgmtNet:false VerifyLinkParams:0xc000c82d15} Client:0xc000b6cfa0 mgmt:0xc00083eb40}

DEBU[0000] Error opening host DNS config run/systemd/resolve/resolv.conf: open run/systemd/resolve/resolv.conf: no such file or directory

DEBU[0000] Filter key: label, filter value: containerlab=$CLAB_HOSTNAME_PREFIX`

The "$CLAB_HOSTNAME_PREFIX" value is set for the "name:" field of the lab and worked on the deploy, however when doing a destroy it's taking this value as a literal string instead of an environment variable. This causes the destroy command to fail to find containers to destroy and it exits out with "no containerlab containers found".

**Comment by hellt** [comment]
Hi, I had a look into it, and I think what happens in your case is that you are not exporting the env var in your shell.

Here is how you have to make use of env vars:

1. export the env var
    ```
    export CLAB_NAME=envtest
    ```
2. and with the topo like this
    ```yaml
    name: ${CLAB_NAME}
    topology:
      nodes:
        l1:
          kind: linux
          image: alpine:3
    ```
3. Use it as `sudo -E clab dep -c -t <name>`


Let me know if this helps, I will close it for now, we can reopen if this won't help
