### ISSUE TITLE
Error: failed to lookup link "br-39817017203e": Link not found during deploy on WSL 2

### ISSUE THREAD

**Issue by tasosptl** [srl-labs/containerlab#2092]
Hello,

I have tried to create the Quick Start lab (https://containerlab.dev/quickstart/) on WSL 2 but during the deploy I got this error message:

INFO[0000] Containerlab v0.55.0 started
INFO[0000] Parsing & checking topology file: srlceos01.clab.yml
WARN[0000] failed gleaning v4 and/or v6 addresses from bridge via netlink, falling back to docker network inspect data
Error: failed to lookup link "br-39817017203e": Link not found

Any ideas?

**Comment by hellt** [comment]
Hi

https://containerlab.dev/install/#windows-subsystem-linux-wsl
