### ISSUE TITLE
Clab Graph interface name impossible to read in XRD routers

### ISSUE THREAD

**Issue by fluzzi** [srl-labs/containerlab#2144]
When I graph a topoligy using XRd routers, the interface name (Gi0-0-0-0) get truncated and its impossible to read:

![image](https://github.com/user-attachments/assets/ac305403-7de6-4a8b-af23-a3807d137c91)

**Comment by hellt** [comment]
Hi @fluzzi 
do you use 0.56.0 version?

**Comment by fluzzi** [comment]
I was on 0.55 but updated and still the same
![image](https://github.com/user-attachments/assets/0daa8d31-4ab5-4680-987f-492b33a040c4)

**Comment by hellt** [comment]
Hi @vista- I wonder if this rings a bell? I remember that you did optimizations for interface aliases and graphs, but maybe when the interface (and not its alias) is used, the graph doesn't calculate the label width dynamically?

**Comment by vista-** [comment]
The labels should automatically size based on the label text.

@fluzzi could you please check whether you see these two lines in the graph JS? You can find it in the developer console (F12 in Chrome).

![Screenshot 2024-07-18 at 20 22 49](https://github.com/user-attachments/assets/b5ff5c46-b2f1-4d7f-ae26-fcdc9f23d9c8)

If you don't see them, that means you are either looking at a cached version of the JS file (try Ctrl+F5 / Cmd+R), or the JS file served by Containerlab hasn't been properly updated. You can find the static files served by `containerlab graph` under /etc/containerlab.

**Comment by fluzzi** [comment]
Okay the web was cached in version 0.55, I force a reload with 0.6 and now is solved

thanks!
