### ISSUE TITLE
Can't find bridge

### ISSUE THREAD

**Issue by Ji-Shao** [srl-labs/containerlab#2147]
containerlab didn't find bridge -- ixp-net

~/sros-frr-ixp-lab$ sudo containerlab deploy -t ixp.clab.yml 
[sudo] password for :       
INFO[0000] **Containerlab v0.56.0 started**                 
INFO[0000] Parsing & checking topology file: ixp.clab.yml 
**Error: bridge "ixp-net" referenced in topology but does not exist**
bridge "ixp-net" referenced in topology but does not exist
bridge "ixp-net" referenced in topology but does not exist
bridge "ixp-net" referenced in topology but does not exist

:~/sros-frr-ixp-lab$ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
932663428c9d   bridge    bridge    local
5a2bb4183472   clab      bridge    local
314a9f4bffe5   host      host      local
**eaacd1a8213e   ixp-net   bridge    local**
b69a12a60601   none      null      local

**Linux b2b 5.15.0-116-generic #126-Ubuntu SMP Mon Jul 1 10:14:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux**

~/sros-frr-ixp-lab$ **docker version**
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:01 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:01 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by hellt** [comment]
the bridge is the linux bridge, not the docker network

**Comment by Ji-Shao** [comment]
Thank you for your prompt response.  

sudo apt install bridge-utils
sudo brctl addbr ixp-net

~/sros-frr-ixp-lab$ sudo containerlab deploy -t ixp.clab.yml
....
+---+----------------+--------------+-------------------------------+--------------+---------+----------------+----------------------+
| # |      Name      | Container ID |             Image             |     Kind     |  State  |  IPv4 Address  |     IPv6 Address     |
+---+----------------+--------------+-------------------------------+--------------+---------+----------------+----------------------+
| 1 | clab-ixp-peer1 | 989422ca9ece | crpd:v1                       | juniper_crpd | running | 172.20.20.5/24 | 2001:172:20:20::5/64 |
| 2 | clab-ixp-peer2 | c910d1caf57c | quay.io/frrouting/frr:8.4.1   | linux        | running | 172.20.20.4/24 | 2001:172:20:20::4/64 |
| 3 | clab-ixp-rs1   | 89d0adf5f285 | quay.io/openbgpd/openbgpd:7.9 | linux        | running | 172.20.20.3/24 | 2001:172:20:20::3/64 |
| 4 | clab-ixp-rs2   | d7c5999058ce | ghcr.io/srl-labs/bird:2.13    | linux        | running | 172.20.20.2/24 | 2001:172:20:20::2/64 |
+---+----------------+--------------+-------------------------------+--------------+---------+----------------+----------------------+
