### ISSUE TITLE
manual: wireshark: Edgeshark integration: use `DOCKER_DEFAULT_PLATFORM=` before `docker compose` to avoid macos rosetta problems

### ISSUE THREAD

**Issue by thediveo** [srl-labs/containerlab#2162]
Thanks to an issue reporter on the Edgeshark project we learnt that some Apple ARM-based systems users might have set `DOCKER_DEFAULT_PLATFORM=` to x86-64, this then leads to deployment failures as rosetta seemingly doesn't correctly work with read-only image deployments.

The fix is to simply ensure that `DOCKER_DEFAULT_PLATFORM=` is empty/unset while executing `docker compose`, so the "install" command given on the https://containerlab.dev/manual/wireshark/ page should be modified to read:

```bash
curl -sL \
https://github.com/siemens/edgeshark/raw/main/deployments/wget/docker-compose.yaml \
| DOCKER_DEFAULT_PLATFORM= docker compose -f - up -d
```

Happy clab'ing!

**Comment by hellt** [comment]
thanks for the feedback. We soon will have way more arm64 users, so this will help!
fixed in https://github.com/srl-labs/containerlab/commit/3a9c229d05153af4cac36c8a4ceb4ef16ab09963
