### ISSUE TITLE
Containerlab topology with docker-sonic-vs - Error: failed deploy stage for node ...

### ISSUE THREAD

**Issue by jcremp77** [srl-labs/containerlab#2163]
Hi, followed your tutorials off the Containerlab site for 'sonic-vs'; got the image imported thru Docker, however after 'deploying' it is stuck in a 'created' state, but not 'running'. There were 'deploy stage failures'. The output is below, with the content of the topology file afterwards. Any help would be appreciated, thanks.

// Containerlab Version
     version: 0.56.0
     commit: b593b206
       date: 2024-07-09T15:07:14Z
     source: https://github.com/srl-labs/containerlab
 rel. notes: https://containerlab.dev/rn/0.56/

// Terminal output
_user@userver-1:~/clab-quickstart$ sudo containerlab deploy -t sonic01.clab.yml
INFO[0000] Containerlab v0.56.0 started                 
INFO[0000] Parsing & checking topology file: sonic01.clab.yml 
INFO[0000] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU=1500 
INFO[0000] Creating lab directory: /home/user/clab-quickstart/clab-sonic01 
INFO[0000] Creating container: "sonic1"                 
INFO[0000] Creating container: "sonic2"                 
ERRO[0000] failed deploy stage for node "sonic2": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown 
ERRO[0001] failed deploy stage for node "sonic1": Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown 
INFO[0001] Adding containerlab host entries to /etc/hosts file 
INFO[0001] Adding ssh config for containerlab nodes     
+---+---------------------+--------------+------------------------+----------+---------+----------------+----------------------+
| # |        Name         | Container ID |         Image          |   Kind   |  State  |  IPv4 Address  |     IPv6 Address     |
+---+---------------------+--------------+------------------------+----------+---------+----------------+----------------------+
| 1 | clab-sonic01-sonic1 | 604440ee3166 | docker-sonic-vs:726394 | sonic-vs | created | 172.20.20.3/24 | 2001:172:20:20::3/64 |
| 2 | clab-sonic01-sonic2 | a9c412adc9e6 | docker-sonic-vs:726394 | sonic-vs | created | 172.20.20.2/24 | 2001:172:20:20::2/64 |
+---+---------------------+--------------+------------------------+----------+---------+----------------+----------------------+_

// yaml file
`name: sonic01

topology:
  nodes:
    sonic1:
      kind: sonic-vs
      image: docker-sonic-vs:726394
    sonic2:
      kind: sonic-vs
      image: docker-sonic-vs:726394

  links:
    - endpoints: ["sonic1:eth1", "sonic2:eth1"]`

**Comment by hellt** [comment]
Hi. How did you get/build your image?

**Comment by jcremp77** [comment]
[https://containerlab.dev/manual/kinds/sonic-vs/]

Grabbed the 'target/docker-sonic-vs.gz' file and uploaded it to my Ubuntu server and imported via docker import.

I tested the setup with the Nokia SRL and everything was working with that image.

**Comment by hellt** [comment]
try using `docker load -i <tar file>`

**Comment by jcremp77** [comment]
> try using `docker load -i <tar file>`

Awesome that worked thank you!
