### ISSUE TITLE
Cisco IOS XRd starts interfaces as shutdown, even if config does not contain shutdown

### ISSUE THREAD

**Issue by 991jo** [srl-labs/containerlab#2165]
I am running labs with Cisco XRd Control Plane v7.11.2.

When I start a new lab all interfaces are shutdown.

I can then configure `no shutdown`, however when I destroy and deploy the lab again all my links are shutdown again, even if that is not a part of the configuration. This is rather annoying.

Here is the excerpt of my config:

```
interface GigabitEthernet0/0/0/2
 ipv4 point-to-point
 ipv4 unnumbered Loopback0
 ipv6 enable
!
```

And that's what's in the config after destory + deploy:

```
interface GigabitEthernet0/0/0/2
 ipv4 point-to-point
 ipv4 unnumbered Loopback0
 ipv6 enable
 shutdown
!
```

Everything else I have set is still in place as intended, so the config itself is loaded as intended.
Is there a way to work around this in containerlab?

**Comment by hellt** [comment]
Hi @991jo 
are you saying that your config that you persist on the xrd device is rendered as intended after you redeploy, but in addition to your config the `shutdown` statement is added after the redeploy?

**Comment by kaelemc** [comment]
@991jo I'm not seeing this behaviour on XRd vCP 7.10.2. This is kind of weird as I believe on the physical platforms if you don't explicitly `no shut` the interface is down by default.

**Comment by hellt** [comment]
feel free to reopen when you have more data @991jo
