### ISSUE TITLE
FRR containers complain about 'stupidly large' max files limit

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#2217]
https://github.com/srl-labs/containerlab/blob/fbca124ea958b1c9fabd7585cabe76933ba68004/runtime/docker/docker.go#L44

FRR suggests 100000 as a reasonable value

```2024/09/30 20:10:11 [YDG3W-JND95] FD Limit set: 1048576 is stupidly large.  Is this what you intended?  Consider using --limit-fds also limiting size to 100000```

**Comment by hellt** [comment]
this was done in https://github.com/srl-labs/containerlab/pull/825 by @LimeHat to solve #824 

I doubt it will cause any issues with FRR, but lower rlimits used to cause issues with ceos and FRR in the past.

**Comment by jbemmel** [comment]
Turns out the ```1048576``` value does not come from Containerlab, it passes on the default received from the OS

To adjust: add ```root hard nofile 100000``` to /etc/security/limits.conf
