### ISSUE TITLE
Need a nerd knob to disable auto-restart policy of containers of Linux kind

### ISSUE THREAD

**Issue by ipspace** [srl-labs/containerlab#2233]
Linux containers (which include FRRouting nodes) are restarted after a server reboot, but other containers are not, usually resulting in a broken lab. The configuration is gone anyway, and the connectivity (veth pairs) is most probably missing.

Worst case, if a Linux-based container manages to crash your server (if anyone can explain why I'm experiencing that I'll be forever grateful), you could get stuck in an infinite loop and own an expensive brick.

I understand the reasoning behind restarting Linux containers, but it would be great if that would be configurable. Please note that this is different from the **auto-remove** option. I would love to see why a container crashes (great for troubleshooting), I would just need a mechanism to influence its restart.

Finally, FWIW, it looks like https://github.com/srl-labs/containerlab/blob/794e3cb36401bedd2fae73816963c42661fde371/runtime/docker/docker.go#L506 sets **on-restart** policy to **on-failure**, but Docker nonetheless restarts them after the system crash (contrary to https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy)

**Comment by steiler** [comment]
Oh no, again, kind specific config in a general purpose struct...
I'm trying hard since quite a while to erase those types of polution.

**Comment by steiler** [comment]
Hi @ipspace,
well seeing the code I am sad again, having these kind specific knobs in the general runtimes is just ugly and I try since quite a while to get rid of them (although a blame shows my name besides that line .... which I think is due to moving the func around).
I have a pretty hacky solution for you.
Check it out and let me know if that works fine for you or not.
```
mava@server01:~/projects/containerlab3$ cat lab-examples/linux.clab.yml
name: linuxfrr

topology:
  kinds:
    linux:
      image: alpine
  nodes:
    frr1:
      kind: linux
    frr2:
      kind: linux
    host:
      kind: host
      stages:
        configure:
          wait-for: 
          - node: frr1
            stage: configure
          - node: frr2
            stage: configure
          exec:
            on-enter:
              - docker update --restart=on-failure clab-linuxfrr-frr1
              - docker update --restart=on-failure clab-linuxfrr-frr2
mava@server01:~/projects/containerlab3$ 
mava@server01:~/projects/containerlab3$ sudo clab deploy -t /home/mava/projects/containerlab3/lab-examples/linux.clab.yml --reconfigure
INFO[0000] Containerlab v0.57.2 started                 
INFO[0000] Parsing & checking topology file: linux.clab.yml 
INFO[0000] Destroying lab: linuxfrr                     
INFO[0002] Removed container: clab-linuxfrr-frr2        
INFO[0002] Removed container: clab-linuxfrr-frr1        
INFO[0002] Removing containerlab host entries from /etc/hosts file 
INFO[0002] Removing ssh config for containerlab nodes   
INFO[0002] Removing /home/mava/projects/containerlab3/clab-linuxfrr directory... 
INFO[0002] Creating lab directory: /home/mava/projects/containerlab3/clab-linuxfrr 
INFO[0002] Creating container: "frr2"                   
INFO[0002] Creating container: "frr1"                   
INFO[0005] Executed command "docker update --restart=on-failure clab-linuxfrr-frr1" on the node "host". stdout:
clab-linuxfrr-frr1 
INFO[0005] Executed command "docker update --restart=on-failure clab-linuxfrr-frr2" on the node "host". stdout:
clab-linuxfrr-frr2 
INFO[0005] Adding containerlab host entries to /etc/hosts file 
INFO[0005] Adding ssh config for containerlab nodes     
INFO[0005] 🎉 New containerlab version 0.58.0 is available! Release notes: https://containerlab.dev/rn/0.58/
Run 'containerlab version upgrade' to upgrade or go check other installation options at https://containerlab.dev/install/ 
+---+--------------------+--------------+--------------------+-------+---------+----------------+----------------------+
| # |        Name        | Container ID |       Image        | Kind  |  State  |  IPv4 Address  |     IPv6 Address     |
+---+--------------------+--------------+--------------------+-------+---------+----------------+----------------------+
| 1 | Host               | N/A          | Ubuntu 22.04.5 LTS | host  | running | N/A            | N/A                  |
| 2 | clab-linuxfrr-frr1 | 16a35a14bf01 | alpine             | linux | running | 172.20.20.3/24 | 2001:172:20:20::3/64 |
| 3 | clab-linuxfrr-frr2 | 1c842a97524c | alpine             | linux | running | 172.20.20.6/24 | 2001:172:20:20::6/64 |
+---+--------------------+--------------+--------------------+-------+---------+----------------+----------------------+
mava@server01:~/projects/containerlab3$ docker inspect clab-linuxfrr-frr1 | grep RestartPolicy -A3
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
```

**Comment by steiler** [comment]
At some point I had envisioned another field of host-exec like in the node definitions, that would execute commands in the host context and would not require the detour of adding the host node seperately. Then these docker updates could be defined per Node itself oder via magic vars even on the kind... but I could not find any such implementation, so we must have not gotten to it.

**Comment by steiler** [comment]
Welcome!
Let's see what @hellt thinks about #2238.
Maybe we have the nicer solution in the next release.

**Comment by hellt** [comment]
yep, it looks proper
I will have to do docs
