### ISSUE TITLE
Cleanup fails when bind files are no longer available

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#2298]
During ```sudo clab destroy --cleanup -t lab.yml```:
```
Error: failed to verify bind path: stat /home/jeroen/Projects/netlab/tests/clab_files/xr/daemons: no such file or directory
```

Such errors aren't critical when doing 'destroy', and shouldn't stop the process

**Comment by hellt** [comment]
yes, this needs to be addressed
like a parameter to the NewContainerlab that would switch off validations. Destroy routing should set it
