### ISSUE TITLE
SSH public key authentication not configured properly on nodes with SR Linux version prior to 23.10

### ISSUE THREAD

**Issue by guicale** [srl-labs/containerlab#2303]
I'm running a SR Linux 23.7 node on clab 0.59 and SSH public key authentication is not properly configured, with the authorized keys not being configured inside the container, despite `.ssh/authorized_keys` being present in my home directory. The issue is not present if the node is running version 23.10 or above, in which case the authorized keys are properly configured for both the linux user `linuxadmin` and the SRL CLI user `admin`.

According to the [documentation for the SR Linux kind](https://containerlab.dev/manual/kinds/srl/#authorized-keys), the authorized keys for SSH public key authentication should be bind mounted to the home directories of the default SR Linux users (admin and linuxadmin). However, despite the `authorized_keys` file being created in the lab directory, I cannot find the file anywhere within the container, and the bind mount is also not reported by  `docker inspect container`.

In addition, as per [the code](https://github.com/srl-labs/containerlab/blob/aaee747c7a12cb323af1997471729dd912fdbc80/nodes/srl/version.go#L157), the authorized keys are only added through the SR Linux CLI on versions 23.10 and above, although this type of configuration seems to be supported on prior versions.

**Comment by hellt** [comment]
Hi @guicale 
that is correct, we removed the old way of mounting the keys to the linux subsystem in the recent containerlab version to only support the configuration-based key provisioning.

**Comment by guicale** [comment]
Thanks for the quick reply. It seems that versions prior to 23.10 don't support configuring the `admin` and `linuxadmin` authorized keys from the SRL CLI, although the path is available in the YANG tree in version 23.7 despite not being supported, according to the release notes for that version.
If they are not bind mounted to the container and configuring them through the SRL CLI is not supported, I assume it's not possible to provision SSH authorized keys on versions of SR Linux prior to 23.7.

**Comment by hellt** [comment]
You can also use an older containerlab version where we still mount the keys 

I don't recall exactly when I removed it, but something like 0.51 should work

**Comment by guicale** [comment]
Unless I'm missing something, it seems to have been removed on the latest release, v0.59, as per the release notes, more specifically in commit b4da97c.
Also, for anyone else who comes across this issue, the previous behavior can be replicated on the latest version of clab by adding the following to your SRL nodes in the topology file:
 ```
binds:
  - ~/.ssh/authorized_keys:/authorized_keys:ro
exec:
  - mkdir /home/admin/.ssh
  - cp /authorized_keys /home/admin/.ssh/authorized_keys
  - chown -R admin:ntwkadmin /home/admin/.ssh
  - chmod 600 /home/admin/.ssh/authorized_keys
  - mkdir /home/linuxadmin/.ssh
  - cp /authorized_keys /home/linuxadmin/.ssh/authorized_keys
  - chown -R linuxadmin:linuxadmin /home/linuxadmin/.ssh
  - chmod 600 /home/linuxadmin/.ssh/authorized_keys
  - cp /authorized_keys /root/.ssh/authorized_keys
  - chown -R root:root /root/.ssh
  - chmod 600 /root/.ssh/authorized_keys
```
