### ISSUE TITLE
on UTM image debian should be member of docker

### ISSUE THREAD

**Issue by alchemyx** [srl-labs/containerlab#2309]
After following installation process for UTM (MacOS M3) at https://containerlab.dev/install/ there is an UTM image that runs nicely. The only downside is that user debian is not member of group docker so any docker command will fail, so this

```
# import container image and save it under ceos:4.32.0F name
docker import cEOS64-lab-4.32.0F.tar.xz ceos:4.32.0F
```

from https://containerlab.dev/quickstart/#__tabbed_1_1 won't work. 

This can be fixed by doing `usermod -a -G docker debian` and it should be a standard part of that UTM image.

**Comment by hellt** [comment]
will track this progress here https://github.com/srl-labs/containerlab/issues/2310
