### ISSUE TITLE
RHEL 9 deprecating `iptables`

### ISSUE THREAD

**Issue by kaelemc** [srl-labs/containerlab#2318]
On a new Rocky 9.5 install of clab, I noticed I couldn't access lab nodes from my workstation via their IP address directly, and confirmed [iptables rules](https://containerlab.dev/manual/network/#external-access) were installed correctly.

Looks like `iptables` is on it's way out in RHEL. 
- [Rocky docs](https://docs.rockylinux.org/guides/security/enabling_iptables_firewall/)
- [RHEL deprecation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_networking)

My current workaround is to set the default firewalld zone to 'trusted'

```
firewall-cmd --set-default-zone=trusted
firewall-cmd --reload
```

Will have to dig deeper into the specifics...

**Comment by kaelemc** [comment]
On first look, seems the `nftables` things are all there correctly.. admittedly i'm not much of an expert here, but i'll keep digging

**Comment by kaelemc** [comment]
It seems setting the `nftables` rules directly doesn't work. 

Disabling `firewalld` and enabling `nftables` service does the trick. Tested with `external-access: false` to confirm the rules are working.. and behaviour was all correct.

https://access.redhat.com/solutions/7046655

**Comment by hellt** [comment]
I think we use nftables as a first measure and fallback to iptables when nftables is not available.
With that, firewalld needs to be disabled, because having 3 firewall systems is too much

**Comment by hellt** [comment]
I think we use nftables as a first measure and fallback to iptables when nftables is not available.
With that, firewalld needs to be disabled, because having 3 firewall systems is too much

**Comment by kaelemc** [comment]
Yeah definitely, So just document it? log message?

**Comment by hellt** [comment]
yes, looks like a note in the installation guide is needed
