### ISSUE TITLE
/etc/hosts sometimes doesn't get cleaned up on reconfigure/destroy

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#236]
investigation is needed on how to reproduce it

**Comment by steiler** [comment]
I would like to change the way we are doing this. 
I'd basically like to add a header and a footer comment to the blob we are adding containing the entries like
```
###### CLAB-<deploymentname>-START ######
<HOSTS ENTRIES>
###### CLAB-<deploymentname>-END ######
```
On deletion I'd like to search for these comments and delete them along with the content inbetween.

**Comment by hellt** [comment]
I haven't seen this for a while now, will close this and reopen if this will surface again
