### ISSUE TITLE
make cmd field a string list rather than a string

### ISSUE THREAD

**Issue by karimra** [srl-labs/containerlab#253]

**Comment by hellt** [comment]
I wonder if your particular case of making shorted cmd string can instead be more easily solved with YAML multilines?
https://yaml-multiline.info/

**Comment by hellt** [comment]
Hi @karimra 
is this still required given that you can do it like that:

```yaml
cmd: >
  entrypoint.sh
  some-arg1
  some-arg2
```

**Comment by karimra** [comment]
I think there is no need for this. 
The reason I was asking about this is here : https://nickjanetakis.com/blog/docker-tip-63-difference-between-an-array-and-string-based-cmd
But it looks like shlex is taking care of it.
