### ISSUE TITLE
add support for http/https schemas to download topo files on-the-fly

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#344]
to enable sharing of clab files which are self contained

**Comment by steiler** [comment]
Sharing just clab files seems a little oversimplified.
If i'd like to share a lab with you, I'd most probably also want to share the config, to have a starting point or a issue I want you to take a look at.
So we should provide the capability for sharing topo and the lab directory. What do you think?

**Comment by hellt** [comment]
I wanted to start small and do like `kubectl apply -f https://`
this is also useful when the lab has no specific configuration, and just
creates a topology

**Comment by hellt** [comment]
continuation of the discussion in #546
