### ISSUE TITLE
check interfaces signature

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#377]
setting the right interface name for a kind is crucial. A typo in the interface name will break the lab operations.

Proposal is to create a rule set per kind and check the interface signatures before deployment starts

`verifyLinks` function needs to be changed  - https://github.com/srl-labs/containerlab/blob/ae56d5316007f96ee2b5f63ecf2ebb523e9617a7/clab/config.go#L690
instead of ranging over the config of interfaces we shoud range over `c.Links` to have a parsed topology view.

Then in `checkEndpoint` we can get the node Kind for a given endpoint and see if the endpoint name matches the regexp for this particular kind

https://github.com/srl-labs/containerlab/blob/ae56d5316007f96ee2b5f63ecf2ebb523e9617a7/clab/config.go#L827

**Comment by jbemmel** [comment]
Or be lenient and automatically map 'eth1' to 'e1-1', etc. (maybe with a warning)

Use case is the following: I took a topology from https://blog.sflow.com/2021/04/containerlab.html and changed the FRR containers into SRL ones

For most topologies, there should be a small set of interfaces and it's just a linear row. More complex designs (where e1-1 versus e2-1 matters) are different, but more rare
