### ISSUE TITLE
creating virtual wires of type 'bridge' fails

### ISSUE THREAD

**Issue by ackew** [srl-labs/containerlab#388]
For the topo file in attachment, and with version 0.13.0, the connection of bridge virtual wire fails with the error:
INFO[0001] Creating virtual wire: srl04:e1-1 <--> testbridge:eth1
ERRO[0001] could not lookup "srl04": Link not found

The same topology file works with e.g. version 0.9.2.
Am I missing something ? 

Topology file and debug log in attachment.
[topology.yaml.txt](https://github.com/srl-labs/containerlab/files/6335546/topology.yaml.txt)
[deployment_log.txt](https://github.com/srl-labs/containerlab/files/6335556/deployment_log.txt)

**Comment by hellt** [comment]
Hey @ackew 
yes, there was a typo that was fixed in #385 
the release with these changes was not yet issued, as a workaround you can swap the endpoints in your topo file:

```yaml
    - endpoints: ["testbridge:eth1", "srl04:e1-1"]
```

**Comment by ackew** [comment]
Thanks Roman.  Crystal clear !
