### ISSUE TITLE
containerlab inspect "State" enhancement

### ISSUE THREAD

**Issue by thinghacker** [srl-labs/containerlab#407]
When using containerlab inspect and the state is exited, could you consider including additional information e.g. did the container exit cleanly due to someone shutting it down - or due to some kind of exception such as srlinux license key expiry?

**Comment by hellt** [comment]
There is no indication in the container state to tell what caused container to exit.
It is up to the application to indicate the reason for exit in the logs. But checking logs is something that a user needs to do. 

In other words, if container exits unexpectedly, it is for a user to check try he logs and understand the possible reason

**Comment by thinghacker** [comment]
Okay understood, thanks for the explanation.
