### ISSUE TITLE
Code re-organisation

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#415]
Hi 👋 , I'm thinking about extending clab beyond docker to other container runtimes, .e.g. containerd. Reading through the code I've come across a few issues that would make this difficult, so I was going to run a few suggestions by yall first , to see if you're interested in this. The main culprit is the `/clab` directory that tightly integrates container runtime with the rest of the code from this directory so I thought about a few steps how it can be disentangled:

1. Take all of general utility functions, mostly found in `file.go`, `ethtool.go`, maybe `cert.go` and move them into a separate package, e.g. `utils/`
2. Create a new `runtime` package with interface type `ContainerRuntime` that would have a set of common functions , e.g. `CreateContainer`, `ListContainers` and move all Docker API functions behind this interface.

wdyt?

**Comment by hellt** [comment]
Hi @networkop 
That is a good initiative, and something I be been asked of a few times. I can see how both podman and containerd can make a perfect fit for this. 

That is, though, quite a chunk of work, mostly ensuring that the existing functionality works after the split. But I'm willing to dive in with you in this endeavor. 

There's also another piece of decoupling that we were postponing for quite a while, which is the interface based kinds. But this can be done before this I hope

@karimra

**Comment by networkop** [comment]
yeah, i was gonna suggest interfaces for kinds, but then i thought that'd be too much for a single issue. 
anyhow, I think these pieces of work can all be done independently.

**Comment by hellt** [comment]
thanks @networkop for this ginormous contribution!
delivered in #416
