### ISSUE TITLE
Add per-node link count

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#420]
In certain situations, it may be desirable to delay container process initialisation until all links are connected by containerlab. For example, this can be done by passing some env var or a configuration file that the containerised process will be able to understand.
 
However, right now the only meaningful arg in `CreateContainer` is `types.Node` which has no awareness of the number of links it's expected to have. Can we introduce an extra field in the `Node` struct to keep count of the total number of links?
This could be done by incrementing this counter in [here](https://github.com/srl-labs/containerlab/blob/14a2cd0e040941debb597b57efff8d5490e3dc1a/clab/config.go#L536), e.g.

```diff
		for name, n := range c.Nodes {
			if name == split[0] {
				endpoint.Node = n
+                              n.LinkCount++
				break
			}
```

**Comment by hellt** [comment]
yes, that makes sense.
we can also leverage the link count in `vr-xxx` nodes where the desired number of network interfaces can open paths for some improvements.

Do you want to contribute that @networkop ?

**Comment by networkop** [comment]
yep, will add this soon

**Comment by hellt** [comment]
added in #422
