### ISSUE TITLE
Arista cEOS Management IP not showing up

### ISSUE THREAD

**Issue by JB-BR** [srl-labs/containerlab#423]
Hi, 

I am using Containerlab with Arista cEOS (cEOS-lab-4.26.0.1F.tar.xz) and the management IP address is never configured. I need to start the cli (docker exec mycontainer Cli) and set the IP manually for SSH / eAPI to work. 

Any idea why the default template does not set the IP? (this template: https://github.com/srl-labs/containerlab/blob/master/templates/arista/ceos.cfg.tpl)

My clab file: https://github.com/JB-BR/BuildingNetworkAutomationSolutions/blob/master/GettingStarted/DeployNetworkServices/ipsec_ceos.clab.yaml 

Attached an output from my system. 

best regards, 

JB
[output.txt](https://github.com/srl-labs/containerlab/files/6507629/output.txt)

**Comment by hellt** [comment]
Hey @JB-BR 
the fix for this issue is scheduled to be released soon (in v0.14.0)
for now you can download the beta binary from here https://github.com/srl-labs/containerlab/releases/tag/v0.0.0-arista-t2

**Comment by hellt** [comment]
@JB-BR I had pushed 0.14.0 release to which you can upgrade with `containerlab version upgrade`
in 0.14.0 the issue with ceos mgmt interface has been fixed

**Comment by JB-BR** [comment]
@hellt Thank you very much for the quick patch, the startup-config now contains the management ip addresses and ssh (ipv6 and ipv4) from the docker host to the Arista containers works
