### ISSUE TITLE
Refactor CreateContainer to not start the container straight away

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#428]
CreateContainer in docker runtime also starts the container and creates the namespace links.
StartContainer should be called separately, by the core library not implicitly after a create. 

https://github.com/srl-labs/containerlab/blob/4e4df293bd70e4b05cab8b938895e48ace777c37/runtime/docker/docker.go#L251-L261

**Comment by steiler** [comment]
@hellt, @karimra what is your opinion in this?
CreateContainer finally calls StartContainer. In my view we either 
- change it to startContainer and continue with CreateContainer starting it straight away. (Which would basically mean it should be named CreateAndStartContainer but whatever)
- leave it both capital, and change the calling code to first CreateContainer and then StartContainer

We should nevertheless push the above shown code snippet from 257 to 261 into StartContainer since it is less related to the creation.

**Comment by karimra** [comment]
I'm fine with splitting as long as there no side effects
