### ISSUE TITLE
Issue during installation - macOS user

### ISSUE THREAD

**Issue by Spiritus44** [srl-labs/containerlab#464]
Hello,

Thank you for this promising project.
This afternoon I tried to install containerlab (from source) on my macbook pro 2020, I followed the instructions specified on [this page](https://containerlab.srlinux.dev/install/#from-source), so I tried that :

```containerlab [master] go build
go build github.com/containernetworking/plugins/pkg/ns: build constraints exclude all Go files in /Users/XXXXX/go/pkg/mod/github.com/containernetworking/plugins@v0.9.1/pkg/ns
# github.com/srl-labs/containerlab/runtime/containerd
runtime/containerd/containerd.go:171:3: undefined: oci.WithoutRunMount
```

My Macos version is 11.4.

I have the following go version : 
```
containerlab [master] go version
go version go1.16.5 darwin/amd64
```

Do you know how can I successfully install containerlab on my mac ? Should I change my containerd version ?

**Comment by hellt** [comment]
Hi
Thanks for checking containerlab!
Mac OS is not a supported OS, due to the fact that docker doesn't run
natively on os x

**Comment by hellt** [comment]
The way we run containerlab on mac is by launching a VM (i.e. vagrant box or virtualbox/vmware vm)

**Comment by hellt** [comment]
On a mac os docker runs by means of a docker-desktop application, which is not "the native" way to run docker as opposed to running it under linux.

Until docker natively runs on mac, such as it does on linux, or until projects like [lima](https://github.com/AkihiroSuda/lima) won't be finilized, we can't have containerlab natively supported on a mac os

**Comment by Spiritus44** [comment]
Ok, I got it, thank you for your help.
