### ISSUE TITLE
Embed default templates in binary file

### ISSUE THREAD

**Issue by nleiva** [srl-labs/containerlab#466]
This might be a crazy idea, but thought I would bring it up anyway. 

I realized you cannot just run the binary to instantiate topologies. You depend on base config templates you store in `/etc/containerlab`.

```bash
⇨  sudo clab deploy --topo topology.yml
INFO[0000] Parsing & checking topology file: topology.yml 
Error: stat /etc/containerlab/templates/arista/ceos.cfg.tpl: no such file or directory
```

Given these files are lightweight, I wonder why not make them part of the binary, making distribution/installation even simpler. In the past, I would use something like [statik](https://github.com/rakyll/statik/) for this, but as of Go 1.16 you can actually use the [embed](https://golang.org/pkg/embed/) library for this purpose. I can work on this if it makes sense to you. 

I see that config templates might become chainable (#384), so in the end, you would end up with config from the embedded file (bare-bones) plus whatever the user provides.

**Comment by hellt** [comment]
Hi @nleiva 
Yes, I have been thinking about this indeed. But back then I haven't quite found enough reasoning to embark on this journey given we support linux systems only and we create deb/rpm packages that handle the extra files containerlab relies on.

But I do agree, that with embed it is easy to make this proposal a reality. At this moment the core of containerlab undergoes a major housekeeping activity, so it makes sense to get back to this once the dust is settled and the API is fixed.

Let me revive this issue when we have a green light

**Comment by nleiva** [comment]
Makes sense, thanks.

**Comment by hellt** [comment]
@nleiva in #479 I have embedded all the templates, so if you take the current master and try building from it, you should be able to run all the nodes without any issues

would appreciate if you give it a try.

**Comment by nleiva** [comment]
Thanks @hellt! I just built from source and I worked fine, no need for `/etc/containerlab` files :+1: 

The other thing I forgot to mention was the `clab` symlink magic you don't have when building from source with just `go build`, which can frustrate users following the documentation that references `clab`. I would either stick to containerlab or make your target binary name `clab` with the `-o` option in the documentation. Either one, just not two different names.

Can you generate a new release/tag with these changes so I can point to it?

**Comment by hellt** [comment]
Thanks for verifying the fix! 

As to the symlink I don't think there is anything to change here. Installation via packages is still the preferred way and it will take care of symlink creation. 
Those who build from source will have to create alias to build with a chosen binary name if needed

**Comment by nleiva** [comment]
Yeah, no change, maybe a note in the documentation, in the [From source](https://containerlab.srlinux.dev/install/#from-source) section that says something like `go build -o clab` instead of just `go build`.

**Comment by hellt** [comment]
Ah, ok, some not on this won't hurt, indeed. But I'd say it shouldn't ultimately be `clab`. 
We use clab and containerlab interchangeably, so what I propose I add there is the following:


---
Note that by default the `go build`  command will produce a binary named `containerlab`. If it is desired to use a shorthand `clab` name, provide the following build command:
```
go build -o /usr/bin/clab
```

**Comment by nleiva** [comment]
Right. I would not include the folder, because then you need `sudo` privilege to write to it. 

Granted, you need `sudo` to run `clab` anyway, however, I think there is potential to remove that requirement in the future (with `podman` instead of `docker`) which we can discuss later on.

**Comment by hellt** [comment]
Fair. I will close that one then and will do the doc update separately
