### ISSUE TITLE
Update json config schema

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#492]
The schema needs to be updated.

Definition of the mgmt bridge is missing.

Anyone else, anything?

**Comment by hellt** [comment]
also I guess

- https://containerlab.srlinux.dev/manual/nodes/#network-mode

**Comment by steiler** [comment]
Adding Reference to keep-mgmt-net comment
 by @hellt in https://github.com/srl-labs/containerlab/issues/462#issuecomment-872211979_

**Comment by hellt** [comment]
ref #517

**Comment by hellt** [comment]
after #517 the only missing thing is network-mode

**Comment by steiler** [comment]
There is a network-mode in the schema, so can you be a little more precise?

https://github.com/srl-labs/containerlab/blob/306ba1c944178f2702a2288f1f80c437bb43412f/schemas/clab.schema.json#L160-L167

**Comment by hellt** [comment]
I missed it :)
