### ISSUE TITLE
decouple ignite nodes deployment from other runtimes

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#493]
As per https://github.com/srl-labs/containerlab/pull/482/files#r664336872 that PR uses a sequential deployment of nodes if it happens that any of the nodes requires ignite runtime

The proposal is to deploy ignite nodes sequentially, whereas the rest of the nodes will still benefit from the concurrent deployment

**Comment by networkop** [comment]
I can work on that.

**Comment by hellt** [comment]
done in #508
