### ISSUE TITLE
Add an option to inject user's public key

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#497]
It'd be nice to be able to inject `~/.ssh/id_rsa.pub` as a bind mount into `~/.ssh/authorized_keys` inside the container based on some CLI flag.

**Comment by hellt** [comment]
Do you want this to be an option so that you won't pollute the clab
definition file with binds?

**Comment by networkop** [comment]
yes, exactly.

**Comment by hellt** [comment]
sound idea

What about the following proposal:

1. the key `--authz-keys` can take a list of paths to public files. By default the single value of `~/.ssh/id_rsa.pub` is assumed
2. the code will take those paths and create will add them to the `defaults` section of the Topology - https://github.com/srl-labs/containerlab/blob/ef66122378cd58905e7ff62d648b2fb0d0432371/types/topology.go#L14
3. with that, the rest of the code won't need to change, as those binds will be processed as usual

**Comment by networkop** [comment]
yeah, makes sense.

**Comment by networkop** [comment]
looking at the current code it looks like default values are [ignired](https://github.com/srl-labs/containerlab/blob/master/types/topology.go#L75) if any other binds are specified. Is this by design?
```go
func (t *Topology) GetNodeBinds(name string) []string {
	if ndef, ok := t.Nodes[name]; ok {
		if len(ndef.GetBinds()) > 0 {
			return ndef.GetBinds()
		}
		if len(t.GetKind(t.GetNodeKind(name)).GetBinds()) > 0 {
			return t.GetKind(t.GetNodeKind(name)).GetBinds()
		}
		return t.GetDefaults().GetBinds()
	}
	return nil
}
```

**Comment by hellt** [comment]
that looks like an error, it needs to be an inheritance chain from defaults->kind->node, with node being most specific

I think as a first iteration we can just append the values from defaults and kinds to the nodes.

**Comment by karimra** [comment]
I think it was intended to be like this, even in earlier code.

**Comment by hellt** [comment]
initially we only added support for binds under either kinds or nodes - https://github.com/srl-labs/containerlab/pull/124
even defaults were not considered to have binds

but now I do not see why we wont just append all the binds all the way from defaults to nodes

**Comment by networkop** [comment]
there's also an issue with `sudo`. You'd need to do `sudo -E` in order to preserve users' home directory (unless you're root in the first place). Does anyone know a better way? I tend to run my linux as a non-privileged user.

**Comment by hellt** [comment]
Does "sudo -E containerlab --authz-keys ~/.ssh/id_rsa.pub" work? Will the
homedir function we use inside clab to parse the homedir correctly?

If yes, what do you want to shorten there?

Maybe sudoers file can somehow implement the preservation of users home dir

**Comment by networkop** [comment]
yes, that command will work, but the flag is easy to forget, hence why I asked if there are any alternatives
modifying sudoers will also work although I dunno how good it is to suggest that -- it effectively means that homedir for sudo will always point to users' homedir which may break other things.

**Comment by hellt** [comment]
In my view that is ok to assume that people will resort to reading docs in
case of failures. In the flag docs we will mention that the sudo users
should either use -E flag with sudo command or they have to provide the abs
path of the private key

**Comment by vincentbernat** [comment]
With `sudo containerlab --authz-keys ~/.ssh/id_rsa.pub`, the `~` is parsed by the shell. Containerlab will see the resolved path, so this is not an issue.

**Comment by networkop** [comment]
I think the problem is that it'll get resolved to `/root` and not `/home/user` where my key is likely to be.

**Comment by vincentbernat** [comment]
No, your shell is running with your identity and `HOME=/home/user`. Your shell will expand `~` to `/home/user`, then provide the arguments to `sudo`.

**Comment by vincentbernat** [comment]
I am interested in doing that. I was about to implement it in vrnetlab, but maybe this is just simpler to let containerlab do that. Just to be sure, my plan was to add the option and implement it for XRv9k and Juniper MX kinds by implementing a `AddSSHKey()` to the node and invoke it if it exists. I am a bit unsure if it is the right approach in case the OS is containarized. Can we also rely on SSH in this case? It's just that bindmount should be defined earlier, but maybe this is not incompatible: for containers, `AddSSHKey()` can stay undefined and the `--authz-keys` parameter can be used earlier by appending to bind mounts.

**Comment by networkop** [comment]
yeah, you're right. I must have dreamt it

**Comment by hellt** [comment]
Hi @vincentbernat 
how did you plan to inject the key into the xrv and vmx? 
it seems that you would need to inject the public key into the configuration of those network systems, and the mechanism to do that is custom per each node

**Comment by hellt** [comment]
for vrnetlab based routers though, it might be more feasible to implemented the code in the launch.py that is part of the vrnetlab image, because then we know when the node is booted and can provision the key

**Comment by vincentbernat** [comment]
I was planning to use SSH and issue the appropriate commands. And same for injecting an initial configuration file. Doing it inside `launch.py` was my initial option. If you think this is better this way, I'll go this way.

**Comment by hellt** [comment]
In #716 I created a `c.Dir.Lab/authorized_keys` file that containers pub keys from all the files found at `~/.ssh` dir

this file can be then mounted to the relevant path inside the particular node if needed. Example - https://github.com/srl-labs/containerlab/pull/716/files#diff-84e2ae483c1b7bb1fe7b4e080f06f3b468a9ff01968d90da1747b0ce2d8acc84R159

**Comment by hellt** [comment]
SR Linux node kind has been updated to mount the generated authorized_keys file
other nodes will be done upon a request
