### ISSUE TITLE
cvx lab-examples topology file ending

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#516]
The topology files for vcx examples end in plain .yml they should probably also be .clab.yml such that the yaml schema will apply.

**Comment by hellt** [comment]
@networkop do you want to take this?

**Comment by networkop** [comment]
yup, give us a minute. what's the significance of that suffix?

**Comment by hellt** [comment]
It will enable json schema live check in VS Code and other editors which
have YAML linter/support plugin installed
