### ISSUE TITLE
Firecracker folder

### ISSUE THREAD

**Issue by nleiva** [srl-labs/containerlab#522]
You are currently ignoring the error when creating the `/var/lib/firecracker` folders with `os.Mkdir` in [iginite.go](../tree/master/runtime/ignite/iginite.go). Could you use [MkdirAll](https://pkg.go.dev/os#MkdirAll) instead, in the case `/var/lib/firecracker` doesn't exist, so you can create the parent folder for all these?

```go
var runtimePaths = []string{
	"/var/lib/firecracker/vm",
	"/var/lib/firecracker/image",
	"/var/lib/firecracker/kernel",
}

...

// ensure firecracker directroy
for _, path := range runtimePaths {
    if _, err := os.Stat(path); os.IsNotExist(err) {
        os.Mkdir(path, os.ModeDir)
    }
}
```

cc @networkop

**Comment by hellt** [comment]
thanks @nleiva 
fixed in 0.15.1
