### ISSUE TITLE
a new `host` kind

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#542]
Right now we use `kind: linux` to emulate end clients/nodes/servers. One [common challenge](https://github.com/networkop/cx/issues/1) with this kind is applying its startup configuration. Even if the configuration is injected at create time, the container will boot before all of the extra links are connected and, hence, the startup configuration needs to be re-applied again.
One [solution](https://github.com/networkop/cx/blob/main/host/entrypoint.sh) for that is to pass an extra argument to the container (or it could be env var) that would tell the entrypoint to wait until a certain number of interfaces are connected before applying the startup config. So my suggestion is to create a new special kind (or modify linux kind) that would pass some metadata to the container (most likely via env vars so that existing cmd/args are not affected). So, for example, for this new kind clab would calculate how many extra interfaces are expected to be connected and pass it into the container in `CLAB_EXTRA_INTFS` env var and, assuming the container understands it, it can decide to wait for some time until all these extra intfs are connected.

The benefit of this approach vs `linux` kind with explicitly interface number specified in `cmd` is the ease of use. There's no reliance on user to specify the right amount of extra intfs, they all get calculated by clab and guaranteed to be correct.

P.S. I can see there's an [existing](https://github.com/srl-labs/containerlab/blob/master/nodes/host/host.go) `host` kind however it's not documented and doesn't look like it's doing anything. we can either build on top of that or create another kind called `server`?

**Comment by hellt** [comment]
It looks like a comkon "issue" with Linux kind containers, so I'd rather
lean towards making an env var that will make a container of Linux kind to
wait for all it's interfaces to appear before executing a command directive

What do you think?

Also there is no entry point that we can use with nodes at this moment,
only cmd...


PS: how do you think this can be done? Injecting a script that goes first
before the command specified in CMD?

**Comment by networkop** [comment]
Yep, env vars seems like the best option. In fact, we _could_ make this a default for all containers (regardless of kind). this could make [these kinds of problems](https://github.com/srl-labs/containerlab/issues/513#issuecomment-881411383) easier to solve. 

As for the how to make it wait. The easiest way is to say "build your entrypoint against our env var API". For example, for `host:ifreload` this would be a minor change.

But I think there could be a generic way to do it. Override the entrypoint and inject some ugly bash one-liner that would first wait and then apply the old entrypoint and pass it all of the args from cmd.

**Comment by hellt** [comment]
Ah, ok, I'm totally fine with making that hidden env var for all kinds and
adapting entry point per image

Adding to an existing entry point automatically at first looks complicated.
We can't guarantee it is bash that calls it even... So I'd say doing and
incremental thing with env var seems like the decent way to proceed with it

**Comment by networkop** [comment]
fixed in #548
