### ISSUE TITLE
Proposal: add exec property to nodes component

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [srl-labs/containerlab#598]
### Problem that this proposal tries to solve
Currently user can specify custom `cmd` for a `node` component. It sets/overrides command specified in container image. But there's no option for the case when user would want to execute additional commands. 

For example, in my lab i use [this image](https://github.com/panubo/docker-sshd/blob/master/Dockerfile) and additionally want to execute `python` installation command. Initial Dockerfile defines `CMD`, so to keep it, i have to run it in new command also. Final cmd looks `bash -c "apk add python3 && /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config"`.

IMO, that's quite inconvenient and it would be great if it be possible to specify additional commands to execute in container, that would not override original image command.

### Proposed solution
Docker has [exec](https://docs.docker.com/engine/reference/commandline/exec/) command that runs command in a running container.  It should be possible to implement similar behavior in containerlab.
 
`exec` list field could be added to a `node` component. Which would look like this:
```
nodes:
  node1:
    exec:
     - bash cmd1.sh
     - bash cmd2.sh
```
Unlike `cmd` field, entries in `exec` field will be executed in running container, without overriding initial command.

**Comment by hellt** [comment]
thanks for the valuable contribution @GrigoriyMikhalkin 
since #602 is now merged, I close this
