### ISSUE TITLE
Request: Add Support for aarch64 

### ISSUE THREAD

**Issue by JulioPDX** [srl-labs/containerlab#605]
Hello All,

I tried installing containerlab on a pinebook pro and received the following error. If this is not possible please feel free to close issue. Thank you for creating container lab!

```bash
[juliopdx@pbpro srl-ceos-gobgp]$ bash -c "$(curl -sL https://get-clab.srlinux.dev)"
No prebuilt binary for linux-aarch64.
To build from source, go to https://github.com/srl-labs/containerlab
Failed to install containerlab
        For support, go to https://github.com/srl-labs/containerlab/issues
[juliopdx@pbpro srl-ceos-gobgp]$ 
```

**Comment by hellt** [comment]
Hi @JulioPDX 
Although it is possible to build arm64 image for containerlab, you won't find network os images in that architecture. 

You would be able to build the vrnetlab based images I think, but not sure if that's enough for you

**Comment by JulioPDX** [comment]
Hi @hellt 

I should be good. I'll have to mess with a different architecture to get it running. Thanks you
