### ISSUE TITLE
make `destroy` command to use relative paths as referenced in topo file

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#607]
if a topo file contains a relative path to some bind mount, then when doing `destroy -a` while not being in the same directory where the local path can be resolved, clab will fail.

The destroy needs to somehow change into the directory from which the `deploy` command was called to resolve the paths and destroy the lab succesfully

**Comment by hellt** [comment]
@karimra  I wanted to revive the thought of destroying the lab without reading the topo file -> just by removing containers.
But I think the problem is that we now can have runtimer per node (i.e. docker + ignite), thus we somehow need to get the runtime of the node without reading the topology...

**Comment by karimra** [comment]
It should be possible to list all the containers in both runtimes and delete those with label `containerlab=${LAB_NAME}`

**Comment by hellt** [comment]
fixed in #814
