### ISSUE TITLE
failed deploy phase for node "mysocketio": Error response from daemon: OCI runtime create failed: container_linux.go:380:

### ISSUE THREAD

**Issue by fredsem** [srl-labs/containerlab#627]
I have the following topology:

> name: lab01
> mgmt:
>   ipv4_subnet: 10.10.10.0/24
> topology:
>   nodes:
>     R01:
>       kind: vr-sros
>       publish:
>         - tcp/22
>       image: vrnetlab/vr-sros:20.10.R1
>       license: ../licenses/SR_OS_VSR_license.txt
>     R02:
>       kind: vr-sros
>       publish:
>         - tcp/22
>       image: vrnetlab/vr-sros:20.10.R1
>       license: ../licenses/SR_OS_VSR_license.txt
>     mysocketio:
>       kind: mysocketio
>       image: ghcr.io/hellt/mysocketctl:0.4.0
>       binds:
>         - .mysocketio_token:/root/.mysocketio_token
>    links:
>     - endpoints: ["R01:eth1","R02:eth4"]`

But when I try to deploy the topology, I got the following error:

> [root@mylab topologies]# containerlab deploy --topo lab01.yml 
> INFO[0000] Parsing & checking topology file: lab01.yml  
> INFO[0000] Creating lab directory: /opt/mylab/SROS_LABs/topologies/clab-lab01 
> INFO[0000] Creating docker network: Name='clab', IPv4Subnet='10.10.10.0/24', IPv6Subnet='', MTU='1500' 
> INFO[0000] Creating container: mysocketio               
> INFO[0000] Creating container: R02                      
> INFO[0000] Creating container: R01                      
> **ERRO[0006] failed deploy phase for node "mysocketio": Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown** 
> INFO[0006] Creating virtual wire: R01:eth1 <--> R02:eth4 
> **ERRO[0006] failed to run postdeploy task for node mysocketio: failed to disable tx checksum offload for mysocketio kind: failed to Statfs "": no such file or directory** 
> INFO[0006] Adding containerlab host entries to /etc/hosts file 
> +---+-----------------------+--------------+---------------------------------+------------+---------+---------------+--------------+
> | # |         Name          | Container ID |              Image              |    Kind    |  State  | IPv4 Address  | IPv6 Address |
> +---+-----------------------+--------------+---------------------------------+------------+---------+---------------+--------------+
> | 1 | clab-lab01-R01        | 5115a1066664 | vrnetlab/vr-sros:20.10.R1       | vr-sros    | running | 10.10.10.3/24 | NA           |
> | 2 | clab-lab01-R02        | 3e83b759365f | vrnetlab/vr-sros:20.10.R1       | vr-sros    | running | 10.10.10.4/24 | NA           |
> | 3 | clab-lab01-mysocketio | fc497e7001c3 | ghcr.io/hellt/mysocketctl:0.4.0 | mysocketio | created | 10.10.10.2/24 | NA           |
> +---+-----------------------+--------------+---------------------------------+------------+---------+---------------+--------------+
> **ERRO[0006] failed to create exec in container /clab-lab01-mysocketio: Error response from daemon: Container fc497e7001c376ba86cdf6fafc4b1efb8b4d16eb5162c8015c5cce759cd9f62d is not running** 

How can I fix this issue?.

Thanks.

**Comment by hellt** [comment]
Hi @fredsem 
I will have a look at this

**Comment by hellt** [comment]
@fredsem there was a regression in 0.18 unfortunately
you may want to downgrade to 0.17 with

```
bash -c "$(curl -sL https://get-clab.srlinux.dev)" -- -v 0.17.0
```

where this issue shouldn't be seen. I will fix it in the next release
