### ISSUE TITLE
Sonic entrypoint & post-deploy

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#677]
👋  quick question about sonic:
what's the reason for doing `/bin/bash` as the entrypoint and then starting supervisord in post-deploy action?
why not make supervisord the entrypoint ?

**Comment by hellt** [comment]
Likely a legacy from the times when Sonic was initially adopted to
containerlab and things were tried in different ways.
If you can give it a spin with supd as an entry point and that will work,
then it should be the default

**Comment by networkop** [comment]
nope, looks like it's there for a reason. if supervisord starts early, it will fail to detect additional interfaces. So post-deploy seems like the best option to start it.
