### ISSUE TITLE
user-defined post-deploy actions

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#695]
👋 , not sure if this is already supported? in case not, it'd be nice to have a way to inject some post-deploy commands , e.g. specifically thinking about kubeadm to turn linux nodes into k8s nodes automatically.

**Comment by hellt** [comment]
Yo. Yes, exec must be something you're looking for https://containerlab.srlinux.dev/manual/nodes/#exec

**Comment by networkop** [comment]
ack. thanks :+1
