### ISSUE TITLE
temprorary topology file isn't cleaned

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [srl-labs/containerlab#699]
At 0.20 release containerlab started to create additional topology file with `.` prefix after execution of any command using `--topo` flag.

From what i understand, it's intent was to serve as a temporary file in case topo file was downloaded. But instead it creates this dotted file even when topo file is local.

If i'm correct regarding the purpose of this file, my proposal is to:

1) don't create file in case local topo file is used
2) don't create this file at all? -- use internal structure directly

**Comment by hellt** [comment]
We still need it though.
Mostly for two reasons

1. As a backup for the original topology. More often that we wanted it to
be users change the original topo file mid-flight. This makes it impossible
to delete the lab as the lab contents changed. The backup file resolves
that issue as users can restore from it

2. The generated topologies that were added in 0.20 take a template file
and a vars file to generate a Topology file. This Topology still needs to
be a file that clab will take in and deploy.
This case can be handled without a physical file, but it is more involved,
so the initial approach was to still create a real Topology file
