### ISSUE TITLE
integrate topology viewer based on NextUI

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#703]
There is another topology visualization framework - NextUI - that can build networking topologies in a nice layout

![image](https://user-images.githubusercontent.com/5679861/143847957-cfca9a51-8293-4e48-b3ef-d474727d9b1c.png)

It has been used in a popular netbox plugin - https://github.com/iDebugAll/nextbox-ui-plugin - to visualise topologies based on data extracted from netbox.
This work is based on a prototype built [here](https://github.com/iDebugAll/devnet_marathon_endgame) and explained in details [here](https://habr.com/ru/post/501164/) (Ru lang)

The way this tool works is that it takes a topology definition structure like pictured below and builds an HTML file with NextUI JS powering the toplogy.

```js
var topologyData = {
    "links": [
        {
            "id": 0,
            "source": 7,
            "srcDevice": "edge-sw01.devnet.lab",
            "srcIfName": "Gi0/2",
            "target": 5,
            "tgtDevice": "core-rtr01.devnet.lab",
            "tgtIfName": "Gi0/0/0/1"
        },
        {
            "id": 1,
            "source": 7,
            "srcDevice": "edge-sw01.devnet.lab",
            "srcIfName": "Gi0/3",
            "target": 3,
            "tgtDevice": "core-rtr02.devnet.lab",
            "tgtIfName": "Gi0/0/0/1"
        },
        {
            "id": 2,
            "source": 4,
            "srcDevice": "dist-rtr01.devnet.lab",
            "srcIfName": "Gi3",
            "target": 3,
            "tgtDevice": "core-rtr02.devnet.lab",
            "tgtIfName": "Gi0/0/0/2"
        },
        {
            "id": 3,
            "source": 4,
            "srcDevice": "dist-rtr01.devnet.lab",
            "srcIfName": "Gi4",
            "target": 1,
            "tgtDevice": "dist-sw01.devnet.lab",
            "tgtIfName": "Eth1/3"
        },
        {
            "id": 4,
            "source": 4,
            "srcDevice": "dist-rtr01.devnet.lab",
            "srcIfName": "Gi6",
            "target": 0,
            "tgtDevice": "dist-rtr02.devnet.lab",
            "tgtIfName": "Gi6"
        },
        {
            "id": 5,
            "source": 4,
            "srcDevice": "dist-rtr01.devnet.lab",
            "srcIfName": "Gi5",
            "target": 2,
            "tgtDevice": "dist-sw02.devnet.lab",
            "tgtIfName": "Eth1/3"
        },
        {
            "id": 6,
            "source": 4,
            "srcDevice": "dist-rtr01.devnet.lab",
            "srcIfName": "Gi2",
            "target": 5,
            "tgtDevice": "core-rtr01.devnet.lab",
            "tgtIfName": "Gi0/0/0/2"
        },
        {
            "id": 7,
            "source": 0,
            "srcDevice": "dist-rtr02.devnet.lab",
            "srcIfName": "Gi3",
            "target": 3,
            "tgtDevice": "core-rtr02.devnet.lab",
            "tgtIfName": "Gi0/0/0/3"
        },
        {
            "id": 8,
            "source": 0,
            "srcDevice": "dist-rtr02.devnet.lab",
            "srcIfName": "Gi4",
            "target": 1,
            "tgtDevice": "dist-sw01.devnet.lab",
            "tgtIfName": "Eth1/4"
        },
        {
            "id": 9,
            "source": 0,
            "srcDevice": "dist-rtr02.devnet.lab",
            "srcIfName": "Gi5",
            "target": 2,
            "tgtDevice": "dist-sw02.devnet.lab",
            "tgtIfName": "Eth1/4"
        },
        {
            "id": 10,
            "source": 0,
            "srcDevice": "dist-rtr02.devnet.lab",
            "srcIfName": "Gi2",
            "target": 5,
            "tgtDevice": "core-rtr01.devnet.lab",
            "tgtIfName": "Gi0/0/0/3"
        },
        {
            "id": 11,
            "source": 1,
            "srcDevice": "dist-sw01.devnet.lab",
            "srcIfName": "Eth1/1",
            "target": 2,
            "tgtDevice": "dist-sw02.devnet.lab",
            "tgtIfName": "Eth1/1"
        },
        {
            "id": 12,
            "source": 1,
            "srcDevice": "dist-sw01.devnet.lab",
            "srcIfName": "Eth1/2",
            "target": 2,
            "tgtDevice": "dist-sw02.devnet.lab",
            "tgtIfName": "Eth1/2"
        }
    ],
    "nodes": [
        {
            "icon": "router",
            "id": 0,
            "model": "CSR1000V",
            "name": "dist-rtr02.devnet.lab",
            "serial_number": "9YZKNQKQ566",
            "layerSortPreference": 7,
            "primaryIP": "10.10.20.176",
            "dcimDeviceLink": "http://localhost:32768/dcim/devices/?q=dist-rtr02.devnet.lab"
        },
        {
            "icon": "switch",
            "id": 1,
            "model": "Nexus9000 9000v Chassis",
            "name": "dist-sw01.devnet.lab",
            "serial_number": "9MZLNM0ZC9Z",
        },
        {
            "icon": "switch",
            "id": 2,
            "model": "Nexus9000 9000v Chassis",
            "name": "dist-sw02.devnet.lab",
            "serial_number": "93LCGCRUJA5",
        },
        {
            "icon": "router",
            "id": 3,
            "model": "n/a",
            "name": "core-rtr02.devnet.lab",
            "serial_number": "n/a",
        },
        {
            "icon": "router",
            "id": 4,
            "model": "CSR1000V",
            "name": "dist-rtr01.devnet.lab",
            "serial_number": "9S78ZRF2V2B",
        },
        {
            "icon": "router",
            "id": 5,
            "model": "n/a",
            "name": "core-rtr01.devnet.lab",
            "serial_number": "n/a",
        },
        {
            "icon": "router",
            "id": 6,
            "model": "CSR1000V",
            "name": "internet-rtr01.virl.info",
            "serial_number": "9LGWPM8GTV6",
        },
        {
            "icon": "switch",
            "id": 7,
            "model": "IOSv",
            "name": "edge-sw01.devnet.lab",
            "serial_number": "927A4RELIGI",
        }
    ]
};
```

Containerlab can generate the `nextuiTopology.json` file similar to the example above and generate the resulting HTML along with serving it

**Comment by bortok** [comment]
I’d like to propose the following workflow:



1. A user runs “`containerlab graph --json`” command to export topology data structure in the same JSON format as used for built-in HTML rendering
2. After that, a separate utility could be used to read the JSON file, transform the data into CMT format used by NeXt UI and render NeXt UI visualization pages
3. The visualization pages could then be served via any type of web server

The benefits of this workflow are:



* No dependencies on NeXt UI are added to Containerlab
* No need to implement a consistent logic of creating node and interface identifiers for CMT format, especially given NeXt UI’s capabilities to show changes of a topology over time that depend on those identifiers. Isolate such implementation into a separate utility
* Least amount of new code
* The same workflow could be used with other visualization engines without any additional changes

The disadvantages are:



* A user would have to install and learn to use a separate utility to generate NeXt UI visualization
* In certain cases a user would have to launch a web server to serve the visualization pages

There is one data element that it would be useful to add into the JSON data structure – a custom label to define an icon to use for a node. I suggest to either include all labels into the JSON export, or only those with a specific prefix, like it is done today for ansible.

**Comment by hellt** [comment]
@bortok that all makes sense 
I think in my personal workflow I'd package the transformation logic and the webserver into a separate container so that users would be able to do a docker run and get a ready made http page to browse

**Comment by ahmedalodhari** [comment]
I think it's best to use a single tool for both building and visualizing the network topology. 

Containerlab already generates the topology definition in the required format for NextUI via the `{data}` object. What's missing is the ability to serve static files and remove the dependency for an external web server. The `net/http` go web server has this capability and we can enable it by making minor modification to the `graph` code as shown [here](https://github.com/srl-labs/containerlab/compare/main...ahmedalodhari:graph-serve-static-files). 

Then, we can generate and serve a network topology graph using `containerlab graph --topo topo.clab.yml --template custom_template.html --static-dir ./assets`.

I have already tested this approach and an example of the topology visualization using NextUI  is shown below:

![containerlab_topo_with_nextui](https://user-images.githubusercontent.com/11521160/155654224-d46b346d-7051-49f8-ba93-6dee6d22a39f.gif)

You can find more info about the template used above from this [repo](https://github.com/ahmedalodhari/Containerlab_NextUI_Template).

**Comment by hellt** [comment]
Hey @ahmedalodhari nice to see you here!
It makes sense, I agree
Do you want to create a PR, it seems everything is ready =)

**Comment by hellt** [comment]
The nextui embedded template proposed by @ahmedalodhari has been merged, and now it is a default graph option in containerlab

With the next release the nextui framework will be installed with containerlab by `/etc/containerlab/templates/graph/nextui` path

The feedback I collected around the proposed template is aggregated here #818. Unfortunately I do not have JS skills to work on that myself, so I resort to contributors to steer this forward
