### ISSUE TITLE
Enhancement: Do not prefix the "name" of the topology to the nodes, just like prefix: "" works

### ISSUE THREAD

**Issue by dharmbhai** [srl-labs/containerlab#723]
It would be ultra low priority Enhancement request. Nice to have.
At times, there arent many overlapping topology running and hence wish to have the node name be as it is defined. 
i.e Dont want name and prefix to be applied to node name.
Just the node name verbatim

Perhaps , this could be implemented using some flag which enables / disables the application of
1) "name" to node name
2) and/or "prefix" to node name.

**Comment by hellt** [comment]
done in 0.22.0
the empty prefix will now strip lab name prefix as well
