### ISSUE TITLE
add support for `restart=always` node parameter

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#744]
currently containerlab with docker runtime schedules containers without `restart=always` policy (https://docs.docker.com/engine/reference/commandline/run/#restart-policies---restart). This might be particularly interesting for `linux` kind nodes, which we typically want to have restarted if they fail for whatever reason.

The quick solution would be to set this mode for any `linux` kind nodes, without bother adding configuration option for that.

**Comment by LimeHat** [comment]
Hmm. I think you may encounter an issue there -> since all but one interfaces are managed by clab (in a stateless manner); you'll be losing them during these restarts (same thing as we discussed recently - netns lifetime = container lifetime).

**Comment by hellt** [comment]
yes, the caveats will be documented.
this is primarily needed for regular linux containers with a single management interface (db, telemetry stacks, etc), to ensure the continuity of their's lifetime should they decide to shit the bed

**Comment by hellt** [comment]
in #777 I added the `on-failure` restart policy for linux kind specifically. It seems there little to know reason to add this for regular NOSes, as they typically have some datapath interfaces which is painful to re-create should the node be restarted.

Hence, only nodes of linux kind will have this restart policy by default.
