### ISSUE TITLE
explore the option to start containers after the veth links attachment

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#754]
Currently, clab deploys containers and starts them. After they have been started, clab adds veth interfaces to it.
Explore the option to start the containers after the interfaces attachment.

**Comment by hellt** [comment]
yes, that is what my quick test showed as well

It is connected to #687 where it seems ixia-c container needs to have interfaces connected before starting the main process.
I will ask for more information, but if that is the case, we would need to change the entrypoint to inject a script that will wait for the needed number of interfaces to become provisioned, before starting the main entrypoint

**Comment by LimeHat** [comment]
> we would need to change the entrypoint to inject a script that will wait for the needed number of interfaces to become provisioned, before starting the main entrypoint

You are correct, sir. Overriding an entrypoint (with either timer-based wait, although not a fool proof; or a script-based tracking) is the most straightforward solution for this.

I can add custom namespaces for podman, but probably it doesn't make too much sense to have 2 different solutions especially if this is only a single tool that needs this.

**Comment by user318** [comment]
Is there some "standard" way for such script to verify that all required interfaces are created? May be some type of signaling (touch some file, etc.)? Or can I pass the list of interfaces as some environment variable?

**Comment by user318** [comment]
I've found in the environment an undocumented variable `CLAB_INTFS` that seems to contain the number of interfaces.

**Comment by hellt** [comment]
@user318 yes, we use this number of interfaces to hold on image boot up before we see those interfaces connected
