### ISSUE TITLE
Add an option to skip the PostDeploy 

### ISSUE THREAD

**Issue by bjmeuer** [srl-labs/containerlab#768]
In some cases the PostDeploy is not needed and only takes time to run. In our Ansible automation we bring up labs on several containerlab notes in sequence and with the postDeploy we need to wait for it to be finished to move on from one containerlab host to the next one. Additionally in our case we provide a full startup-config with the same management ip for a node as set in the topology file. Therefore there seems not real benefit of PostDeploy. 

I would like to introduce a new option to the deploy command to skip the PostDeploy. Only if that option is set the PostDeploy should be skipped, the default behaviour of running it should stay like it is today.

**Comment by hellt** [comment]
Hi @bjmeuer 
which nodes/kind do you use specifically?

**Comment by hellt** [comment]
sounds good, can you make a Pull Request so that I can have a look?
I would imagine this CLI option would be named `--skip-post-deploy`

**Comment by bjmeuer** [comment]
> sounds good, can you make a Pull Request so that I can have a look? 

Pull request added
