### ISSUE TITLE
Running containerlab 0.23.0 on WSL2/Ubuntu with cEOS

### ISSUE THREAD

**Issue by bgolab** [srl-labs/containerlab#774]
Hi,

I am looking for detailed procedure how to install the containerlab on WSL2 for cEOS. What I did so far:

1. **I have NO issues with running the containerlab 0.23.0 on ubuntu VM ran on VirtualBox hosted by W10**.
I deployed  two cEOS (arista) containers, configured IPv4/IPv6. Works smoothly - I mean I can ping both containers from each other.

2. I wanted to install the same lab on WSL2/ubuntu and followed the procedure from the web site.
The cEOS containers seem to run without any issues. (Docker Engine - Community, Engine: 20.10.12)
But I see two connectivity issues here
- I configured IPv4 but **I cannot ping the the Eth1 neither the management interfaces from the containers**. The arp shows relevant entries! . But there is no connectivity through ping
- I configured IPv6 but I do not see IPv6 neighbors neither I cannot ping the other containers
---------------------------
Before I start debugging the docker itself I would like know if someone managed to use cEOS (arista containers) on WSL2/ubuntu.

Thanks you
Bogdan

**Comment by hellt** [comment]
Hi @bgolab 
it was discussed in containerlab discord
seems to be related with some incompatibility of WSL kernel features and ceos expectations.
Looks like one could solve it by adding an ALLOW action for iptables inside ceos
<img width="674" alt="image" src="https://user-images.githubusercontent.com/5679861/153612506-a9b540e8-a2db-4a81-8df6-79c1e3caa89b.png">

**Comment by bgolab** [comment]
1. IPv4 connectivity was **fixed** by applying
sudo iptables -P INPUT ACCEPT

2. IPv6 was fixed partially by applying
sudo ip6tables -P INPUT ACCEPT

Partially because:
- IPv6 neighbors are seen - both GLA and LLA
ceos1#sh ipv6 neighbors
IPv6 Address                                  Age Hardware Addr    State Interface
2001::2                                   0:04:36 aac1.ab72.217b   REACH Et1
fe80::a8c1:abff:fe72:217b                 0:05:55 aac1.ab72.217b   REACH Et1

- GLA are pinged
ceos1#ping 2001::2
[...]
5 packets transmitted, 5 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.017/0.043/0.120/0.039 ms, ipg/ewma 0.098/0.080 ms

- LLA are NOT pinged (fe80::21c:73ff:fe5b:de77)
ceos1#ping fe80::a8c1:abff:fe72:217b
connect: Invalid argument

**Comment by bgolab** [comment]
It looks like the LLA requires the interface specified:

ping fe80::a8c1:abff:fe72:217b interface ethernet 1
works.

**Comment by bgolab** [comment]
Solution above

**Comment by hellt** [comment]
great, I will document those iptables commands for ceos nodes.

**Comment by bgolab** [comment]
Thank you for your first pointer! This got me started;)
