### ISSUE TITLE
make iptables rules management fail gracefully

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#797]
Quite often users install docker via a package manager. Sometimes this results in docker to be installed without docker-managed iptables rules in place.

We need not to stop deployment/destroy when iptables errors occur, instead we should emit a warning error and keep moving

**Comment by LimeHat** [comment]
Docs say that both chains are used by docker?
https://docs.docker.com/network/iptables/

> Docker installs two custom iptables chains named DOCKER-USER and DOCKER, and it ensures that incoming packets are always checked by these two chains first.

> All of Docker’s iptables rules are added to the DOCKER chain. Do not manipulate this chain manually. If you need to add rules which load before Docker’s rules, add them to the DOCKER-USER chain. These rules are applied before any rules Docker creates automatically.

Agree on the last point.

**Comment by hellt** [comment]
Looks like the originally reported issue was captured on a system where
chains were manually screwed up. Will update this when I get more details.

As of now it seems when people install docker via apt/yum the docker chains
are not there. Maybe something like docker service is missing with such
installations, not sure

**Comment by LimeHat** [comment]
Maybe https://github.com/docker/for-linux/issues/810

**Comment by LimeHat** [comment]
Ok so docker-user first became available in [17.06 ](https://github.com/docker/docker-ce/commit/6345212aa25c6e06e396cf8a2cbc85d4559464fe)

**Comment by hellt** [comment]
great. It is a miracle clab even worked with docker-1.13.1
the warn error has been added in https://github.com/srl-labs/containerlab/pull/798/commits/465a83bb617b145a8b7eacad4359dfcd0c3d70c3
