### ISSUE TITLE
Duplicate Management Address Checks

### ISSUE THREAD

**Issue by JulioPDX** [srl-labs/containerlab#812]
This is more to protect the user. I made the mistake of copy pasta and tried deploying a lab with duplicate management IPs. Nodes had static assignments. I think it would be good to protect the user and add a duplicate address check before deployment. Thank you!

**Comment by hellt** [comment]
good idea!
I think maybe someone can take a stab at this
@bclasse do you maybe want to flex your go muscles a bit?
