### ISSUE TITLE
add a check for sse3 cpu instruction availability 

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#837]
sse3 instructions must be available for nodes which are based on dpdk
it can be missing if users deploy/use a VM that was created with some old CPU emulated. It is easy to fix with running a VM that has full cpu host support

the check must be done during the topology checks stage, the lab must be halted if sse3 is missing and srl nodes are part of the topology and we must emit the warning message otherwise

**Comment by nemith** [comment]
This doesn't work well for docker in docker or docker in lima as the SSE3 will be done at the docker level.

**Comment by hellt** [comment]
@nemith I'll check if disabling sse3 cpu capability check will work, testing it on srlinux in dind
