### ISSUE TITLE
clab/config.go remove dependency on Kind Constants

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#845]
In clab/config.go we rely on the Kind consts for bridge ovs, host and srl type.
These should be changed. The functionality should probably be added to the node implementations itself (when it comes to the srl related stuff) or should be indicated via a boolean flag on the Kind, like an "isBridge" flag  for the bridge or ovs-bridge type of kind.
which is then checked in this case:
https://github.com/srl-labs/containerlab/blob/main/clab/config.go#L411-L421

**Comment by steiler** [comment]
in #828 I would rather then from a central spot stating requirements of certain kinds introduce a `MinCPURequired` flag with anything above 0 being a valid requirement. And then loop through all the kinds of that certain topology and check perform the check... thats the better and more generic approach

**Comment by hellt** [comment]
@steiler after the recent PRs do we still have this dependency?

**Comment by steiler** [comment]
Yes, that is resolved.
Just realized that there is some stuff remaining, that can be removed.
see #1227
