### ISSUE TITLE
vrnetlab veos errors out during boot

### ISSUE THREAD

**Issue by notworker123** [srl-labs/containerlab#859]
veos version: vEOS-lab-4.27.3F.vmdk
host os: ubuntu 20.0 bullseye/sid
containerlab-version: custom build from last issue to address cEOS interfaces not being created

[veos-docker-logs.txt](https://github.com/srl-labs/containerlab/files/8482565/veos-docker-logs.txt)

full logs attached. relevant output below:

2022-04-13 15:08:43,416: vrnetlab   INFO     Unable to connect to qemu monitor (port 5000), retrying in a second (attempt 59)
2022-04-13 15:08:44,417: vrnetlab   INFO     Unable to connect to qemu monitor (port 5000), retrying in a second (attempt 60)
Traceback (most recent call last):
  File "/launch.py", line 191, in <module>
    vr.start()
  File "/vrnetlab.py", line 686, in start
    vm.work()
  File "/vrnetlab.py", line 617, in work
    self.check_qemu()
  File "/vrnetlab.py", line 631, in check_qemu
    self.start()
  File "/vrnetlab.py", line 205, in start
    raise QemuBroken(
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 5000

**Comment by notworker123** [comment]
my mistake. i put the wrong version in at the top. i am running veos w/ vrnetlab.

veos version: vEOS-lab-4.27.3F.vmdk

docker images
REPOSITORY                  TAG         IMAGE ID       CREATED             SIZE
vrnetlab/vr-veos            4.27.3F     71a0eab610d6   About an hour ago   926MB


name: vmx-vr-veos-ubuntu
yaml file output: 

topology:
  nodes:
    r1-lf01:
      kind: vr-veos
      image: vrnetlab/vr-veos:4.27.3F

    r1-lf02:
      kind: vr-veos
      image: vrnetlab/vr-veos:4.27.3F
      env:
        BOOT_DELAY: 10

**Comment by notworker123** [comment]
server has nothing else running on it. the server's specs are:

dual Intel 8260 w/ 384 GB of RAM

i try to start w/ just two leafs and same issue:

name: leaf-to-leaf

topology:
  nodes:
    r1-lf01:
      kind: vr-veos
      image: vrnetlab/vr-veos:4.27.3F

    r1-lf02:
      kind: vr-veos
      image: vrnetlab/vr-veos:4.27.3F
      env:
        BOOT_DELAY: 10

  links:
    # leaf to leaf
    - endpoints: ["r1-lf01:eth1","r1-lf02:eth1"]

i will dig around some more when i have more free time. thanks for the ideas.

**Comment by hellt** [comment]
you can also ask for help at discord
we had no issues so far with veos image built with hellt/vrnetlab, so that is highly likely related to the specific host settings of your lab
