### ISSUE TITLE
Podman runtime issues on Fedora 36

### ISSUE THREAD

**Issue by modzilla99** [srl-labs/containerlab#912]
Hey there thank you for providing containerlabs! It's an awesome project but sadly the podman backend on Fedora is not working right.

Here are the problems I faced:

### Image-Pull

Containerlabs can't use podman to pull images that are not in fqdn format because it runs without a tty and podman tries to open a dialogue asking where it should pull the image from.

```shell
$ grep image clab.yml 
      image: networkop/cx:4.3.0
$ containerlab deploy -t clab.yml 
INFO[0000] Containerlab v0.27.1 started                 
INFO[0000] Parsing & checking topology file: clab.yml   
Error: short-name resolution enforced but cannot prompt without a TTY
$
$ grep image clab.yml 
      image: docker.io/networkop/cx:4.3.0
$ containerlab deploy -t clab.yml 
INFO[0000] Containerlab v0.27.1 started                 
INFO[0000] Parsing & checking topology file: clab.yml   
Trying to pull docker.io/networkop/cx:4.3.0...
Getting image source signatures
Copying blob sha256:037bde409e95375706430fda81106acb0b6d8aedad2c6bc77bfc40779060d60e
...
```

### Socket

Containerlabs tries to call docker.sock, but even after activating podman.socket docker.sock won't get created. You can bind mount the socket tho, but that doesn't seem like a good solution and containerlabs should instead just use the correct socket.

```shell
$ touch /var/run/docker.sock
$ mount -o bind /var/run/podman/podman.sock /var/run/docker.sock
```

### Networking

Also networking doesn't work as expected containerlabs throws errors. That might be related to the new netawark backend?!

```shell
$ podman info --debug | grep networkBackend
  networkBackend: netavark
$ containerlab deploy -t clab.yml 
INFO[0023] Creating lab directory: /root/netw/clab-cvx02 
INFO[0023] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU="1500" 
WARN[0023] failed to enable LLDP on docker bridge: open /sys/class/net/br-5e2a1b164bc5/bridge/group_fwd_mask: no such file or directory 
WARN[0023] failed to disable TX checksum offloading for the br-5e2a1b164bc5 bridge interface: no such device 
WARN[0023] errors during iptables rules install: missing DOCKER-USER iptables chain. See http://containerlab.dev/manual/network/#external-access 
ERRO[0023] failed deploy phase for node "sw1": more than one result for network ID  
```
Changing the backend back to CNI doesn't make it any better and throws even more errors... In any case containerlabs just hangs...

```shell
$ podman info --debug | grep networkBackend
  networkBackend: cni
$ grep "^network_backend" /etc/containers/containers.conf.d/network.conf
network_backend = "cni"
$ containerlab deploy -t clab.yml 
WARN[0000] Failed to decode the keys ["network.network_backend"] from "/etc/containers/containers.conf.d/network.conf". 
INFO[0000] Containerlab v0.27.1 started                 
INFO[0000] Parsing & checking topology file: clab.yml   
INFO[0000] Creating lab directory: /root/netw/clab-cvx02 
WARN[0000] failed to enable LLDP on docker bridge: open /sys/class/net/br-64227f557fd8/bridge/group_fwd_mask: no such file or directory 
WARN[0000] failed to disable TX checksum offloading for the br-64227f557fd8 bridge interface: no such device 
ERRO[0000] failed deploy phase for node "sw1": more than one result for network ID  
^C
$
```

Also where the hell did it get the `br-64227f557fd8` bridge name from?! If I'm not mistaken it should `cni-clab0` or similar. At least that's what podman provisioned with it's default podman network `cni-podman0`

**Comment by LimeHat** [comment]
Hi @modzilla99 

I'm so sorry about that! Roman is right indeed, I didn't update the code for v4, it is still on my list. Let me see if I can get it done in a couple of days.

As for more details,
> Containerlabs can't use podman to pull images that are not in fqdn format because it runs without a tty and podman tries to open a dialogue asking where it should pull the image from.

Yeah, I don't think we can work around this limitation in clab. Podman was always designed to work with fqdn-based names (even preferring localhost/ for local ones)
It is possible to reconfigure podman to not enforce the manual choose (and iterate over the list of repos), but I'm not sure we should be reconfiguring users' systems. Probably a better approach would be just to document this.

> Containerlabs tries to call docker.sock, but even after activating podman.socket docker.sock won't get created. You can bind mount the socket tho, but that doesn't seem like a good solution and containerlabs should instead just use the correct socket.
Hmm. I don't think this should be the case; I'll look into it. Thx


> Networking

Yes, this is the (un)fortunate part - networking API got a decent amount of rework between v3 and v4 and became incompatible. The good news is - v4 API is better and allows us to solve some earlier issues.

> Also where the hell did it get the br-64227f557fd8 bridge name from?! If I'm not mistaken it should cni-clab0 or similar. 
In v3 api they didn't allow to set the bridge name, so we had to rely on podman-generated naming.

Thank you so much for the detailed report. I'll provide an update soon.

**Comment by hellt** [comment]
@LimeHat  as for the issue with fqdn names, can't we use the same logic we used for other runtimes?

https://github.com/srl-labs/containerlab/blob/46100ef74a702c2b73af5deba38305b0a2f335ad/utils/containers.go#L15

**Comment by LimeHat** [comment]
Hi @modzilla99 , I submitted a pr (#919) to enable podmanv4 support, will be merged soon.

I want to follow-up on your "docker.sock" comment - are you trying to use containerlab in a container? It is the only reference I see in the our code (our documentation, to be precise) to docker.sock 
If not, something strange is going on.

re
> @LimeHat as for the issue with fqdn names, can't we use the same logic we used for other runtimes?

Hmm. Maybe. Didn't know we had this logic built-in. 
I noticed that on my centos setup, in fact, `"short-name-mode = "permissive"` by default. And it looks up for short names across 4 different registries: `unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "docker.io"]
`
I'll check why do we have this difference between centos & fedora. And if enforcing mode is the new normal - I can add a call to the function as you suggested.

**Comment by hellt** [comment]
@modzilla99 here is a beta build for you to try out fixes that @LimeHat added

With the following pull command you get a containerlab binary at your working directory. To use this downloaded binary - ./containerlab deploy.... Make sure not forget to add ./ prefix in order to use the downloaded binary and not the globally installed containerlab!

```
docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull ghcr.io/srl-labs/clab-oci:c66b5eaf
```

**Comment by hellt** [comment]
With #919 merged we should have initial support for podman v4 and sunsetting v3 
I am closing this issue with a goal to have more rectified issues around podman support in the future
