### ISSUE TITLE
M1 MacBook - Failed to install containerlab

### ISSUE THREAD

**Issue by jvanderaa** [srl-labs/containerlab#927]
1. Navigated to quick start page
2. Run command to get started
3. Receive error message

```
No prebuilt binary for darwin-arm64.
To build from source, go to https://github.com/srl-labs/containerlab
Failed to install containerlab
	For support, go to https://github.com/srl-labs/containerlab/issues
```

**Comment by hellt** [comment]
Hi @jvanderaa 
M1 is not supported, I will have to update installation docs with a note on that specifically.

Main reasons:

1. There are no arm64 network images in the wild yet. You can play with FRR and maybe sonic, but that's it... Rosetta virtualisation won't cut it here. So no use case for containerlab...
2. Apple requires developers to sign binaries for arm64 arch, which requires Apple Dev account, which costs mon€y. Given 1) there is no reason to get on this journey as of yet.

PS. One can build arm64 binary themselves from Go code, should they have a particular arm64 image they want to play with

**Comment by jvanderaa** [comment]
All good. There were no issues (closed or opened) when I searched for `M1`. And there was nothing noted on the quick start guide. Since the M1 architecture has been around for a while an issue was opened.
