### ISSUE TITLE
No way to disable logging, especially when using JSON output

### ISSUE THREAD

**Issue by mk-fg** [srl-labs/containerlab#956]
Hi,

Trying to use containerlab 0.29 with "inspect -f json", I always get INFO lines in stdout, which prevents it being parseable as JSON, which contradicts the apparent intent of "-f json" option.
And more generally, a way to configure console output to only print errors would be useful, as otherwise they'll get lost among noisy info output, which also trains user to always ignore it (as is sensible, it being noise in 99.99% cases).

- What I did: `clontainerlab i --all -f json` with no labs running.
- Expected output: `[]` or nothing.
- Actual output: `INFO[0000] no containers found`, which is not valid JSON.
- Steps to reproduce: run `clontainerlab inspect -f json` - always prints INFO lines, which are never valid JSON.
- Setup info: containerlab 0.29 (c0055a03) installed via official docker container.

Thanks.

**Comment by hellt** [comment]
Hi @mk-fg 
valid points. Right now `inspect -f json` is not producing a json file when there are no containers found, true. It makes sense to change that indeed.

As for the quiet mode I also think it makes sense to add that as a `-q` global flag that will set the logger to Warn+ level

**Comment by mk-fg** [comment]
Another simple tweak that comes to mind, and first one that I've tried for separating JSON from logging, is using stderr stream for all logging (like e.g. python logging framework does by default), while reserving stdout for any other deliberate/expected output - tables, json, etc.
This way, any wrapper tool interested in parsing JSON can read it from stdout, while printing buffered stderr logging only if there's anything unexpected (with JSON, exit code or otherwise).

**Comment by hellt** [comment]
that is actually how it was supposed to be.
It seems that in the process of some refactoring there has been a regression

**Comment by hellt** [comment]
@mk-fg download this beta build with the following command

```
docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull ghcr.io/srl-labs/clab-oci:fd237d21
```

the new bin has a new global flag `--log-level` that takes in `warn`, `error`, `debug`, `info` values.
Additionally, log messages are output to stderr

**Comment by mk-fg** [comment]
This should indeed fix the issue, thanks.

I think you did forget to change option description on this line though:
`rootCmd.PersistentFlags().StringVarP(&logLevel, "log-level", "", "info", "container runtime")`
Should probably be something like: logging output verbosity (debug, info, warn, error, fatal, default=info)
