### ISSUE TITLE
No way to disable automatic version checks via github when using "deploy" command

### ISSUE THREAD

**Issue by mk-fg** [srl-labs/containerlab#957]
Hi,

When running `containerlab deploy`, tool always makes an external http request to github.com, which appears to be a mandatory version check (via `go getLatestVersion(vCh)` call in deploy.go) to print information message about new version being available.

When running a managed clab instance of specific version on an isolated network, neither extraneous http call to external API nor a version check and notification are desirable, so maybe there should be a way to disable this somehow?

Easiest and least-intrusive way I can think of might be a documented variable in a clab YAML file (read by same "deploy" command) or a documented environment variable (e.g. CLAB_DISABLE_VERSION_CHECK).

- What I did: run `containerlab deploy`
- Expected result: no external http requests to any third parties from containerlab binary, stable reproducible output, related to deployment process and configuration.
- Actual result: external http request upon running command, spurious unrelated `🎉 New containerlab version ... is available! Release notes: ...`  output printed sometimes, both can't seem to be disabled via containerlab itself.
- Setup: containerlab 0.29.0 (c0055a03) installed via official docker container, with 0.30.0 version available upstream.

Thanks!

**Comment by steiler** [comment]
well it would then even be container host dependent and not dependent on the topology you run. Hence, it should become an environement variable. This can be set per host and will persist reboots and so on.

**Comment by steiler** [comment]
Here is the related PR.

https://github.com/srl-labs/containerlab/pull/959

if you run this with sudo make sure to set the env var in the root context. Was my initial issue when testing.

`sudo CLAB_VERSION_CHECK=disable ./containerlab deploy -t ....`

**Comment by mk-fg** [comment]
It looks great, thank you.
I've added a comment on the PR about some basic documentation of this flag, but dunno if maybe it's too esoteric to bother adding doc section over.
