### ISSUE TITLE
Not all VM kinds support startup-config

### ISSUE THREAD

**Issue by nlgotz** [srl-labs/containerlab#973]
From a testing/usability perspective, it would be awesome if all of the VM kinds would support a startup config.

Going through the code briefly, here's where it looks like is currently supported or not supported

| Kind                      | startup-config Support |
|---------------------------|---------|
| Nokia SROS                | Yes     |
| Arista vEOS               | No     |
| Juniper vMX               | Partial     |
| Juniper vQFX              | Yes     |
| Cisco XRv                 | No     |
| Cisco XRv9k             | No |
| Cisco CSR                 | No     |
| Cisco Nexus                | No     |
| Cisco Nexus 9000v         | No     |
| Dell FTOS10v              | No     |
| Mikrotik RouterOS         | Yes     |
| Palo Alto PAN             | No     |
| IPInfusion OcNOS          | No     |
| Checkpoint Cloudguard     | No     |

From looking at the code, it looks like vMX has support in Containerlab (doesn't look like it in hellt/vrnetlab).

Things Needed for Containerlab:

- [ ] Code for all "No" nodes
- [ ] Update Documentation

This won't fully allow all nodes to load a startup config as changes will need to be done on the hellt/vrnetlab and/or boxen end to actually do something with the config file

**Comment by nlgotz** [comment]
This is something I can take on/be assigned.

I see this as being 1 PR to add the code and then separate PRs to update the documentation once the vrnetlab/boxen portion gets updated.

**Comment by hellt** [comment]
Hi @nlgotz 
currently most (like 90%) of non-sros vrnetlab images uses the following technique to deliver the stratup-config functionality:

1. containrelab refers a file which contains CLI based lines
2. vrnetlab code opens this file and pushes it line by line when the node applies it default config (like [here](https://github.com/hellt/vrnetlab/blob/master/vqfx/docker/launch.py#L156-L178))

are you planning on using this one?

**Comment by nlgotz** [comment]
Yep. I was planning on basically copy/pasting how it's done in the vmx/vqfx go files and then in vrnetlab loading it line by line.

I may redo the RouterOS one as well so that it uses the same method and doesn't require tftp or anything like that to load configs. But that'd be lower on my priority list as it's already working

**Comment by hellt** [comment]
ok, cool
on clab side that can be a single PR (with docs) after the relevant parts are merged into vrnetlab
you will be able to create a clab binary with those changes without releasing it, so you can test vrnetlab part

**Comment by nlgotz** [comment]
#977 fixes most of the nodes with the exception of a few:

vrnetlab: 
- Dell FTOS - I'm working on trying to get a workable image. Shouldn't be difficult as the CLI is very Cisco like
- Palo Alto PAN - I don't have access to an image

I haven't done/am unable to do much with Boxen as the builds fail before any sort of modification, making it impossible to test/validate

**Comment by nlgotz** [comment]
Updated #977 to include Dell FTOS as I was able to get it working and tested

**Comment by hellt** [comment]
these changes has been merged into 0.31.1
thank you

**Comment by achurak** [comment]
Just tested with Cisco CSR and it doesn't seem to work, what am I missing? I do see the `config` directory created under the node's name and my custom config copied into it as `startup-config.cfg` however none of the config is applied to the node.

I do see in the debug `DEBU[0000] node 'node2-2' generated config:` with my custom config, but that's it. I don't see any errors either.

**Comment by hellt** [comment]
@achurak 
have you re-generated the csr image using the latest hellt/vrnetlab master branch?

**Comment by achurak** [comment]
> @achurak have you re-generated the csr image using the latest hellt/vrnetlab master branch?

Nope, but now that you say this it does make sense I need to regenerate the image, might make sense to add a small note in the release notes or the documentation. Thanks!

**Comment by achurak** [comment]
> @achurak have you re-generated the csr image using the latest hellt/vrnetlab master branch?

Nope, but now that you say this it does make sense I need to regenerate the image, might make sense to add a small note in the release notes or the documentation. Thanks!

**Comment by hellt** [comment]
closing as delivered
