### ISSUE TITLE
crpd startup-configs affect crpd nodes without it 

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#987]
As [reported](https://discord.com/channels/860500297297821756/865572929601142845/1012583627600711690) in discord, there seems to be an issue with crpd nodes that use startup-config affect the other crpd nodes that don't have it.

test lab that exhibits this behavior - https://github.com/netatteh/clab-crpd-test

**Comment by hellt** [comment]
Hi @netatteh, thanks for the MVP of a bug, it helps a lot.

Could you please try a beta build where I think I fixed this


```
With the following pull command you get a containerlab binary at your working directory. To use this downloaded binary - ./containerlab deploy.... Make sure not forget to add ./ prefix in order to use the downloaded binary and not the globally installed containerlab!
If https proxy is configured in your environment, pass the proxies via --env HTTPS_PROXY="<proxy-address>" flag of the docker run command.

docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull ghcr.io/srl-labs/clab-oci:7d3337d1
```

**Comment by netatteh** [comment]
Hi! Confirmed with https://github.com/netatteh/clab-crpd-test and the new binary, the `startup-config` is now working as expected. Thank you!
